//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591

namespace Sigeor.Reportes.EorCabeceraTransitoReport {
    
    
    /// <summary>
    ///Represents a strongly typed in-memory cache of data.
    ///</summary>
    [global::System.Serializable()]
    [global::System.ComponentModel.DesignerCategoryAttribute("code")]
    [global::System.ComponentModel.ToolboxItem(true)]
    [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedDataSetSchema")]
    [global::System.Xml.Serialization.XmlRootAttribute("EorDetalleTransitoReportDataSet")]
    [global::System.ComponentModel.Design.HelpKeywordAttribute("vs.data.DataSet")]
    public partial class EorDetalleTransitoReportDataSet : global::System.Data.DataSet {
        
        private GET_DETALLE_EOR_TRANSITODataTable tableGET_DETALLE_EOR_TRANSITO;
        
        private global::System.Data.SchemaSerializationMode _schemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public EorDetalleTransitoReportDataSet() {
            this.BeginInit();
            this.InitClass();
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            base.Relations.CollectionChanged += schemaChangedHandler;
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected EorDetalleTransitoReportDataSet(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                base(info, context, false) {
            if ((this.IsBinarySerialized(info, context) == true)) {
                this.InitVars(false);
                global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler1 = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
                this.Tables.CollectionChanged += schemaChangedHandler1;
                this.Relations.CollectionChanged += schemaChangedHandler1;
                return;
            }
            string strSchema = ((string)(info.GetValue("XmlSchema", typeof(string))));
            if ((this.DetermineSchemaSerializationMode(info, context) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
                if ((ds.Tables["GET_DETALLE_EOR_TRANSITO"] != null)) {
                    base.Tables.Add(new GET_DETALLE_EOR_TRANSITODataTable(ds.Tables["GET_DETALLE_EOR_TRANSITO"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
            }
            this.GetSerializationData(info, context);
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        [global::System.ComponentModel.Browsable(false)]
        [global::System.ComponentModel.DesignerSerializationVisibility(global::System.ComponentModel.DesignerSerializationVisibility.Content)]
        public GET_DETALLE_EOR_TRANSITODataTable GET_DETALLE_EOR_TRANSITO {
            get {
                return this.tableGET_DETALLE_EOR_TRANSITO;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        [global::System.ComponentModel.BrowsableAttribute(true)]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Visible)]
        public override global::System.Data.SchemaSerializationMode SchemaSerializationMode {
            get {
                return this._schemaSerializationMode;
            }
            set {
                this._schemaSerializationMode = value;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataTableCollection Tables {
            get {
                return base.Tables;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataRelationCollection Relations {
            get {
                return base.Relations;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected override void InitializeDerivedDataSet() {
            this.BeginInit();
            this.InitClass();
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public override global::System.Data.DataSet Clone() {
            EorDetalleTransitoReportDataSet cln = ((EorDetalleTransitoReportDataSet)(base.Clone()));
            cln.InitVars();
            cln.SchemaSerializationMode = this.SchemaSerializationMode;
            return cln;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected override bool ShouldSerializeTables() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected override bool ShouldSerializeRelations() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected override void ReadXmlSerializable(global::System.Xml.XmlReader reader) {
            if ((this.DetermineSchemaSerializationMode(reader) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                this.Reset();
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXml(reader);
                if ((ds.Tables["GET_DETALLE_EOR_TRANSITO"] != null)) {
                    base.Tables.Add(new GET_DETALLE_EOR_TRANSITODataTable(ds.Tables["GET_DETALLE_EOR_TRANSITO"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXml(reader);
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected override global::System.Xml.Schema.XmlSchema GetSchemaSerializable() {
            global::System.IO.MemoryStream stream = new global::System.IO.MemoryStream();
            this.WriteXmlSchema(new global::System.Xml.XmlTextWriter(stream, null));
            stream.Position = 0;
            return global::System.Xml.Schema.XmlSchema.Read(new global::System.Xml.XmlTextReader(stream), null);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        internal void InitVars() {
            this.InitVars(true);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        internal void InitVars(bool initTable) {
            this.tableGET_DETALLE_EOR_TRANSITO = ((GET_DETALLE_EOR_TRANSITODataTable)(base.Tables["GET_DETALLE_EOR_TRANSITO"]));
            if ((initTable == true)) {
                if ((this.tableGET_DETALLE_EOR_TRANSITO != null)) {
                    this.tableGET_DETALLE_EOR_TRANSITO.InitVars();
                }
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        private void InitClass() {
            this.DataSetName = "EorDetalleTransitoReportDataSet";
            this.Prefix = "";
            this.Namespace = "http://tempuri.org/EorDetalleTransitoReportDataSet.xsd";
            this.EnforceConstraints = true;
            this.SchemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
            this.tableGET_DETALLE_EOR_TRANSITO = new GET_DETALLE_EOR_TRANSITODataTable();
            base.Tables.Add(this.tableGET_DETALLE_EOR_TRANSITO);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        private bool ShouldSerializeGET_DETALLE_EOR_TRANSITO() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        private void SchemaChanged(object sender, global::System.ComponentModel.CollectionChangeEventArgs e) {
            if ((e.Action == global::System.ComponentModel.CollectionChangeAction.Remove)) {
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedDataSetSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
            EorDetalleTransitoReportDataSet ds = new EorDetalleTransitoReportDataSet();
            global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
            global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
            global::System.Xml.Schema.XmlSchemaAny any = new global::System.Xml.Schema.XmlSchemaAny();
            any.Namespace = ds.Namespace;
            sequence.Items.Add(any);
            type.Particle = sequence;
            global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
            if (xs.Contains(dsSchema.TargetNamespace)) {
                global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                try {
                    global::System.Xml.Schema.XmlSchema schema = null;
                    dsSchema.Write(s1);
                    for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                        schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                        s2.SetLength(0);
                        schema.Write(s2);
                        if ((s1.Length == s2.Length)) {
                            s1.Position = 0;
                            s2.Position = 0;
                            for (; ((s1.Position != s1.Length) 
                                        && (s1.ReadByte() == s2.ReadByte())); ) {
                                ;
                            }
                            if ((s1.Position == s1.Length)) {
                                return type;
                            }
                        }
                    }
                }
                finally {
                    if ((s1 != null)) {
                        s1.Close();
                    }
                    if ((s2 != null)) {
                        s2.Close();
                    }
                }
            }
            xs.Add(dsSchema);
            return type;
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public delegate void GET_DETALLE_EOR_TRANSITORowChangeEventHandler(object sender, GET_DETALLE_EOR_TRANSITORowChangeEvent e);
        
        /// <summary>
        ///Represents the strongly named DataTable class.
        ///</summary>
        [global::System.Serializable()]
        [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedTableSchema")]
        public partial class GET_DETALLE_EOR_TRANSITODataTable : global::System.Data.TypedTableBase<GET_DETALLE_EOR_TRANSITORow> {
            
            private global::System.Data.DataColumn columnNUM_EORTRANSITO;
            
            private global::System.Data.DataColumn columnCOSTOMAOBRA;
            
            private global::System.Data.DataColumn columnCONTAINER;
            
            private global::System.Data.DataColumn columnAPROBADOEST;
            
            private global::System.Data.DataColumn columnAPROBADOMAQ;
            
            private global::System.Data.DataColumn columnTOTAL_COSTOHH;
            
            private global::System.Data.DataColumn columnNOM_LINEA;
            
            private global::System.Data.DataColumn columnNOMBRE_DEPOSITO;
            
            private global::System.Data.DataColumn columnID_EGRPRODUCTO;
            
            private global::System.Data.DataColumn columnID_SECEGRESO;
            
            private global::System.Data.DataColumn columnCOD_DEPOSITO;
            
            private global::System.Data.DataColumn columnID_BODEGA;
            
            private global::System.Data.DataColumn columnID_PRODUCTO;
            
            private global::System.Data.DataColumn columnNOMBRE;
            
            private global::System.Data.DataColumn columnTIPO;
            
            private global::System.Data.DataColumn columnCANTIDAD;
            
            private global::System.Data.DataColumn columnCOSTO;
            
            private global::System.Data.DataColumn columnTOTAL;
            
            private global::System.Data.DataColumn columnCOSTO_IVA;
            
            private global::System.Data.DataColumn columnTOTAL_IVA;
            
            private global::System.Data.DataColumn columnID_SECDANIO;
            
            private global::System.Data.DataColumn columnCANTIDADREAL;
            
            private global::System.Data.DataColumn columnCOSTOREAL;
            
            private global::System.Data.DataColumn columnTOTALREAL;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public GET_DETALLE_EOR_TRANSITODataTable() {
                this.TableName = "GET_DETALLE_EOR_TRANSITO";
                this.BeginInit();
                this.InitClass();
                this.EndInit();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            internal GET_DETALLE_EOR_TRANSITODataTable(global::System.Data.DataTable table) {
                this.TableName = table.TableName;
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected GET_DETALLE_EOR_TRANSITODataTable(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                    base(info, context) {
                this.InitVars();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn NUM_EORTRANSITOColumn {
                get {
                    return this.columnNUM_EORTRANSITO;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn COSTOMAOBRAColumn {
                get {
                    return this.columnCOSTOMAOBRA;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn CONTAINERColumn {
                get {
                    return this.columnCONTAINER;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn APROBADOESTColumn {
                get {
                    return this.columnAPROBADOEST;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn APROBADOMAQColumn {
                get {
                    return this.columnAPROBADOMAQ;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn TOTAL_COSTOHHColumn {
                get {
                    return this.columnTOTAL_COSTOHH;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn NOM_LINEAColumn {
                get {
                    return this.columnNOM_LINEA;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn NOMBRE_DEPOSITOColumn {
                get {
                    return this.columnNOMBRE_DEPOSITO;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn ID_EGRPRODUCTOColumn {
                get {
                    return this.columnID_EGRPRODUCTO;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn ID_SECEGRESOColumn {
                get {
                    return this.columnID_SECEGRESO;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn COD_DEPOSITOColumn {
                get {
                    return this.columnCOD_DEPOSITO;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn ID_BODEGAColumn {
                get {
                    return this.columnID_BODEGA;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn ID_PRODUCTOColumn {
                get {
                    return this.columnID_PRODUCTO;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn NOMBREColumn {
                get {
                    return this.columnNOMBRE;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn TIPOColumn {
                get {
                    return this.columnTIPO;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn CANTIDADColumn {
                get {
                    return this.columnCANTIDAD;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn COSTOColumn {
                get {
                    return this.columnCOSTO;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn TOTALColumn {
                get {
                    return this.columnTOTAL;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn COSTO_IVAColumn {
                get {
                    return this.columnCOSTO_IVA;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn TOTAL_IVAColumn {
                get {
                    return this.columnTOTAL_IVA;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn ID_SECDANIOColumn {
                get {
                    return this.columnID_SECDANIO;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn CANTIDADREALColumn {
                get {
                    return this.columnCANTIDADREAL;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn COSTOREALColumn {
                get {
                    return this.columnCOSTOREAL;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn TOTALREALColumn {
                get {
                    return this.columnTOTALREAL;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            [global::System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public GET_DETALLE_EOR_TRANSITORow this[int index] {
                get {
                    return ((GET_DETALLE_EOR_TRANSITORow)(this.Rows[index]));
                }
            }
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public event GET_DETALLE_EOR_TRANSITORowChangeEventHandler GET_DETALLE_EOR_TRANSITORowChanging;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public event GET_DETALLE_EOR_TRANSITORowChangeEventHandler GET_DETALLE_EOR_TRANSITORowChanged;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public event GET_DETALLE_EOR_TRANSITORowChangeEventHandler GET_DETALLE_EOR_TRANSITORowDeleting;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public event GET_DETALLE_EOR_TRANSITORowChangeEventHandler GET_DETALLE_EOR_TRANSITORowDeleted;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void AddGET_DETALLE_EOR_TRANSITORow(GET_DETALLE_EOR_TRANSITORow row) {
                this.Rows.Add(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public GET_DETALLE_EOR_TRANSITORow AddGET_DETALLE_EOR_TRANSITORow(
                        string NUM_EORTRANSITO, 
                        decimal COSTOMAOBRA, 
                        string CONTAINER, 
                        string APROBADOEST, 
                        string APROBADOMAQ, 
                        decimal TOTAL_COSTOHH, 
                        string NOM_LINEA, 
                        string NOMBRE_DEPOSITO, 
                        string ID_EGRPRODUCTO, 
                        int ID_SECEGRESO, 
                        string COD_DEPOSITO, 
                        int ID_BODEGA, 
                        string ID_PRODUCTO, 
                        string NOMBRE, 
                        string TIPO, 
                        decimal CANTIDAD, 
                        decimal COSTO, 
                        decimal TOTAL, 
                        decimal COSTO_IVA, 
                        decimal TOTAL_IVA, 
                        int ID_SECDANIO, 
                        int CANTIDADREAL, 
                        decimal COSTOREAL, 
                        decimal TOTALREAL) {
                GET_DETALLE_EOR_TRANSITORow rowGET_DETALLE_EOR_TRANSITORow = ((GET_DETALLE_EOR_TRANSITORow)(this.NewRow()));
                object[] columnValuesArray = new object[] {
                        NUM_EORTRANSITO,
                        COSTOMAOBRA,
                        CONTAINER,
                        APROBADOEST,
                        APROBADOMAQ,
                        TOTAL_COSTOHH,
                        NOM_LINEA,
                        NOMBRE_DEPOSITO,
                        ID_EGRPRODUCTO,
                        ID_SECEGRESO,
                        COD_DEPOSITO,
                        ID_BODEGA,
                        ID_PRODUCTO,
                        NOMBRE,
                        TIPO,
                        CANTIDAD,
                        COSTO,
                        TOTAL,
                        COSTO_IVA,
                        TOTAL_IVA,
                        ID_SECDANIO,
                        CANTIDADREAL,
                        COSTOREAL,
                        TOTALREAL};
                rowGET_DETALLE_EOR_TRANSITORow.ItemArray = columnValuesArray;
                this.Rows.Add(rowGET_DETALLE_EOR_TRANSITORow);
                return rowGET_DETALLE_EOR_TRANSITORow;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public GET_DETALLE_EOR_TRANSITORow FindByNUM_EORTRANSITOID_EGRPRODUCTOID_SECEGRESO(string NUM_EORTRANSITO, string ID_EGRPRODUCTO, int ID_SECEGRESO) {
                return ((GET_DETALLE_EOR_TRANSITORow)(this.Rows.Find(new object[] {
                            NUM_EORTRANSITO,
                            ID_EGRPRODUCTO,
                            ID_SECEGRESO})));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public override global::System.Data.DataTable Clone() {
                GET_DETALLE_EOR_TRANSITODataTable cln = ((GET_DETALLE_EOR_TRANSITODataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override global::System.Data.DataTable CreateInstance() {
                return new GET_DETALLE_EOR_TRANSITODataTable();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            internal void InitVars() {
                this.columnNUM_EORTRANSITO = base.Columns["NUM_EORTRANSITO"];
                this.columnCOSTOMAOBRA = base.Columns["COSTOMAOBRA"];
                this.columnCONTAINER = base.Columns["CONTAINER"];
                this.columnAPROBADOEST = base.Columns["APROBADOEST"];
                this.columnAPROBADOMAQ = base.Columns["APROBADOMAQ"];
                this.columnTOTAL_COSTOHH = base.Columns["TOTAL_COSTOHH"];
                this.columnNOM_LINEA = base.Columns["NOM_LINEA"];
                this.columnNOMBRE_DEPOSITO = base.Columns["NOMBRE_DEPOSITO"];
                this.columnID_EGRPRODUCTO = base.Columns["ID_EGRPRODUCTO"];
                this.columnID_SECEGRESO = base.Columns["ID_SECEGRESO"];
                this.columnCOD_DEPOSITO = base.Columns["COD_DEPOSITO"];
                this.columnID_BODEGA = base.Columns["ID_BODEGA"];
                this.columnID_PRODUCTO = base.Columns["ID_PRODUCTO"];
                this.columnNOMBRE = base.Columns["NOMBRE"];
                this.columnTIPO = base.Columns["TIPO"];
                this.columnCANTIDAD = base.Columns["CANTIDAD"];
                this.columnCOSTO = base.Columns["COSTO"];
                this.columnTOTAL = base.Columns["TOTAL"];
                this.columnCOSTO_IVA = base.Columns["COSTO_IVA"];
                this.columnTOTAL_IVA = base.Columns["TOTAL_IVA"];
                this.columnID_SECDANIO = base.Columns["ID_SECDANIO"];
                this.columnCANTIDADREAL = base.Columns["CANTIDADREAL"];
                this.columnCOSTOREAL = base.Columns["COSTOREAL"];
                this.columnTOTALREAL = base.Columns["TOTALREAL"];
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            private void InitClass() {
                this.columnNUM_EORTRANSITO = new global::System.Data.DataColumn("NUM_EORTRANSITO", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnNUM_EORTRANSITO);
                this.columnCOSTOMAOBRA = new global::System.Data.DataColumn("COSTOMAOBRA", typeof(decimal), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnCOSTOMAOBRA);
                this.columnCONTAINER = new global::System.Data.DataColumn("CONTAINER", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnCONTAINER);
                this.columnAPROBADOEST = new global::System.Data.DataColumn("APROBADOEST", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnAPROBADOEST);
                this.columnAPROBADOMAQ = new global::System.Data.DataColumn("APROBADOMAQ", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnAPROBADOMAQ);
                this.columnTOTAL_COSTOHH = new global::System.Data.DataColumn("TOTAL_COSTOHH", typeof(decimal), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnTOTAL_COSTOHH);
                this.columnNOM_LINEA = new global::System.Data.DataColumn("NOM_LINEA", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnNOM_LINEA);
                this.columnNOMBRE_DEPOSITO = new global::System.Data.DataColumn("NOMBRE_DEPOSITO", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnNOMBRE_DEPOSITO);
                this.columnID_EGRPRODUCTO = new global::System.Data.DataColumn("ID_EGRPRODUCTO", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnID_EGRPRODUCTO);
                this.columnID_SECEGRESO = new global::System.Data.DataColumn("ID_SECEGRESO", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnID_SECEGRESO);
                this.columnCOD_DEPOSITO = new global::System.Data.DataColumn("COD_DEPOSITO", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnCOD_DEPOSITO);
                this.columnID_BODEGA = new global::System.Data.DataColumn("ID_BODEGA", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnID_BODEGA);
                this.columnID_PRODUCTO = new global::System.Data.DataColumn("ID_PRODUCTO", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnID_PRODUCTO);
                this.columnNOMBRE = new global::System.Data.DataColumn("NOMBRE", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnNOMBRE);
                this.columnTIPO = new global::System.Data.DataColumn("TIPO", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnTIPO);
                this.columnCANTIDAD = new global::System.Data.DataColumn("CANTIDAD", typeof(decimal), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnCANTIDAD);
                this.columnCOSTO = new global::System.Data.DataColumn("COSTO", typeof(decimal), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnCOSTO);
                this.columnTOTAL = new global::System.Data.DataColumn("TOTAL", typeof(decimal), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnTOTAL);
                this.columnCOSTO_IVA = new global::System.Data.DataColumn("COSTO_IVA", typeof(decimal), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnCOSTO_IVA);
                this.columnTOTAL_IVA = new global::System.Data.DataColumn("TOTAL_IVA", typeof(decimal), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnTOTAL_IVA);
                this.columnID_SECDANIO = new global::System.Data.DataColumn("ID_SECDANIO", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnID_SECDANIO);
                this.columnCANTIDADREAL = new global::System.Data.DataColumn("CANTIDADREAL", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnCANTIDADREAL);
                this.columnCOSTOREAL = new global::System.Data.DataColumn("COSTOREAL", typeof(decimal), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnCOSTOREAL);
                this.columnTOTALREAL = new global::System.Data.DataColumn("TOTALREAL", typeof(decimal), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnTOTALREAL);
                this.Constraints.Add(new global::System.Data.UniqueConstraint("Constraint1", new global::System.Data.DataColumn[] {
                                this.columnNUM_EORTRANSITO,
                                this.columnID_EGRPRODUCTO,
                                this.columnID_SECEGRESO}, true));
                this.columnNUM_EORTRANSITO.AllowDBNull = false;
                this.columnNUM_EORTRANSITO.MaxLength = 13;
                this.columnCONTAINER.ReadOnly = true;
                this.columnCONTAINER.MaxLength = 11;
                this.columnAPROBADOEST.MaxLength = 1;
                this.columnAPROBADOMAQ.MaxLength = 1;
                this.columnNOM_LINEA.AllowDBNull = false;
                this.columnNOM_LINEA.MaxLength = 50;
                this.columnNOMBRE_DEPOSITO.AllowDBNull = false;
                this.columnNOMBRE_DEPOSITO.MaxLength = 30;
                this.columnID_EGRPRODUCTO.AllowDBNull = false;
                this.columnID_EGRPRODUCTO.MaxLength = 15;
                this.columnID_SECEGRESO.AllowDBNull = false;
                this.columnCOD_DEPOSITO.MaxLength = 3;
                this.columnID_PRODUCTO.MaxLength = 15;
                this.columnNOMBRE.MaxLength = 50;
                this.columnTIPO.MaxLength = 1;
                this.columnCANTIDADREAL.ReadOnly = true;
                this.columnCOSTOREAL.ReadOnly = true;
                this.columnTOTALREAL.ReadOnly = true;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public GET_DETALLE_EOR_TRANSITORow NewGET_DETALLE_EOR_TRANSITORow() {
                return ((GET_DETALLE_EOR_TRANSITORow)(this.NewRow()));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override global::System.Data.DataRow NewRowFromBuilder(global::System.Data.DataRowBuilder builder) {
                return new GET_DETALLE_EOR_TRANSITORow(builder);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override global::System.Type GetRowType() {
                return typeof(GET_DETALLE_EOR_TRANSITORow);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override void OnRowChanged(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.GET_DETALLE_EOR_TRANSITORowChanged != null)) {
                    this.GET_DETALLE_EOR_TRANSITORowChanged(this, new GET_DETALLE_EOR_TRANSITORowChangeEvent(((GET_DETALLE_EOR_TRANSITORow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override void OnRowChanging(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.GET_DETALLE_EOR_TRANSITORowChanging != null)) {
                    this.GET_DETALLE_EOR_TRANSITORowChanging(this, new GET_DETALLE_EOR_TRANSITORowChangeEvent(((GET_DETALLE_EOR_TRANSITORow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override void OnRowDeleted(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.GET_DETALLE_EOR_TRANSITORowDeleted != null)) {
                    this.GET_DETALLE_EOR_TRANSITORowDeleted(this, new GET_DETALLE_EOR_TRANSITORowChangeEvent(((GET_DETALLE_EOR_TRANSITORow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override void OnRowDeleting(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.GET_DETALLE_EOR_TRANSITORowDeleting != null)) {
                    this.GET_DETALLE_EOR_TRANSITORowDeleting(this, new GET_DETALLE_EOR_TRANSITORowChangeEvent(((GET_DETALLE_EOR_TRANSITORow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void RemoveGET_DETALLE_EOR_TRANSITORow(GET_DETALLE_EOR_TRANSITORow row) {
                this.Rows.Remove(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedTableSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
                global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
                global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
                EorDetalleTransitoReportDataSet ds = new EorDetalleTransitoReportDataSet();
                global::System.Xml.Schema.XmlSchemaAny any1 = new global::System.Xml.Schema.XmlSchemaAny();
                any1.Namespace = "http://www.w3.org/2001/XMLSchema";
                any1.MinOccurs = new decimal(0);
                any1.MaxOccurs = decimal.MaxValue;
                any1.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any1);
                global::System.Xml.Schema.XmlSchemaAny any2 = new global::System.Xml.Schema.XmlSchemaAny();
                any2.Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1";
                any2.MinOccurs = new decimal(1);
                any2.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any2);
                global::System.Xml.Schema.XmlSchemaAttribute attribute1 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute1.Name = "namespace";
                attribute1.FixedValue = ds.Namespace;
                type.Attributes.Add(attribute1);
                global::System.Xml.Schema.XmlSchemaAttribute attribute2 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute2.Name = "tableTypeName";
                attribute2.FixedValue = "GET_DETALLE_EOR_TRANSITODataTable";
                type.Attributes.Add(attribute2);
                type.Particle = sequence;
                global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
                if (xs.Contains(dsSchema.TargetNamespace)) {
                    global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                    global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                    try {
                        global::System.Xml.Schema.XmlSchema schema = null;
                        dsSchema.Write(s1);
                        for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                            schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                            s2.SetLength(0);
                            schema.Write(s2);
                            if ((s1.Length == s2.Length)) {
                                s1.Position = 0;
                                s2.Position = 0;
                                for (; ((s1.Position != s1.Length) 
                                            && (s1.ReadByte() == s2.ReadByte())); ) {
                                    ;
                                }
                                if ((s1.Position == s1.Length)) {
                                    return type;
                                }
                            }
                        }
                    }
                    finally {
                        if ((s1 != null)) {
                            s1.Close();
                        }
                        if ((s2 != null)) {
                            s2.Close();
                        }
                    }
                }
                xs.Add(dsSchema);
                return type;
            }
        }
        
        /// <summary>
        ///Represents strongly named DataRow class.
        ///</summary>
        public partial class GET_DETALLE_EOR_TRANSITORow : global::System.Data.DataRow {
            
            private GET_DETALLE_EOR_TRANSITODataTable tableGET_DETALLE_EOR_TRANSITO;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            internal GET_DETALLE_EOR_TRANSITORow(global::System.Data.DataRowBuilder rb) : 
                    base(rb) {
                this.tableGET_DETALLE_EOR_TRANSITO = ((GET_DETALLE_EOR_TRANSITODataTable)(this.Table));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string NUM_EORTRANSITO {
                get {
                    return ((string)(this[this.tableGET_DETALLE_EOR_TRANSITO.NUM_EORTRANSITOColumn]));
                }
                set {
                    this[this.tableGET_DETALLE_EOR_TRANSITO.NUM_EORTRANSITOColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public decimal COSTOMAOBRA {
                get {
                    try {
                        return ((decimal)(this[this.tableGET_DETALLE_EOR_TRANSITO.COSTOMAOBRAColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("El valor de la columna \'COSTOMAOBRA\' de la tabla \'GET_DETALLE_EOR_TRANSITO\' es DB" +
                                "Null.", e);
                    }
                }
                set {
                    this[this.tableGET_DETALLE_EOR_TRANSITO.COSTOMAOBRAColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string CONTAINER {
                get {
                    try {
                        return ((string)(this[this.tableGET_DETALLE_EOR_TRANSITO.CONTAINERColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("El valor de la columna \'CONTAINER\' de la tabla \'GET_DETALLE_EOR_TRANSITO\' es DBNu" +
                                "ll.", e);
                    }
                }
                set {
                    this[this.tableGET_DETALLE_EOR_TRANSITO.CONTAINERColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string APROBADOEST {
                get {
                    try {
                        return ((string)(this[this.tableGET_DETALLE_EOR_TRANSITO.APROBADOESTColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("El valor de la columna \'APROBADOEST\' de la tabla \'GET_DETALLE_EOR_TRANSITO\' es DB" +
                                "Null.", e);
                    }
                }
                set {
                    this[this.tableGET_DETALLE_EOR_TRANSITO.APROBADOESTColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string APROBADOMAQ {
                get {
                    try {
                        return ((string)(this[this.tableGET_DETALLE_EOR_TRANSITO.APROBADOMAQColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("El valor de la columna \'APROBADOMAQ\' de la tabla \'GET_DETALLE_EOR_TRANSITO\' es DB" +
                                "Null.", e);
                    }
                }
                set {
                    this[this.tableGET_DETALLE_EOR_TRANSITO.APROBADOMAQColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public decimal TOTAL_COSTOHH {
                get {
                    try {
                        return ((decimal)(this[this.tableGET_DETALLE_EOR_TRANSITO.TOTAL_COSTOHHColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("El valor de la columna \'TOTAL_COSTOHH\' de la tabla \'GET_DETALLE_EOR_TRANSITO\' es " +
                                "DBNull.", e);
                    }
                }
                set {
                    this[this.tableGET_DETALLE_EOR_TRANSITO.TOTAL_COSTOHHColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string NOM_LINEA {
                get {
                    return ((string)(this[this.tableGET_DETALLE_EOR_TRANSITO.NOM_LINEAColumn]));
                }
                set {
                    this[this.tableGET_DETALLE_EOR_TRANSITO.NOM_LINEAColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string NOMBRE_DEPOSITO {
                get {
                    return ((string)(this[this.tableGET_DETALLE_EOR_TRANSITO.NOMBRE_DEPOSITOColumn]));
                }
                set {
                    this[this.tableGET_DETALLE_EOR_TRANSITO.NOMBRE_DEPOSITOColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string ID_EGRPRODUCTO {
                get {
                    return ((string)(this[this.tableGET_DETALLE_EOR_TRANSITO.ID_EGRPRODUCTOColumn]));
                }
                set {
                    this[this.tableGET_DETALLE_EOR_TRANSITO.ID_EGRPRODUCTOColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public int ID_SECEGRESO {
                get {
                    return ((int)(this[this.tableGET_DETALLE_EOR_TRANSITO.ID_SECEGRESOColumn]));
                }
                set {
                    this[this.tableGET_DETALLE_EOR_TRANSITO.ID_SECEGRESOColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string COD_DEPOSITO {
                get {
                    try {
                        return ((string)(this[this.tableGET_DETALLE_EOR_TRANSITO.COD_DEPOSITOColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("El valor de la columna \'COD_DEPOSITO\' de la tabla \'GET_DETALLE_EOR_TRANSITO\' es D" +
                                "BNull.", e);
                    }
                }
                set {
                    this[this.tableGET_DETALLE_EOR_TRANSITO.COD_DEPOSITOColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public int ID_BODEGA {
                get {
                    try {
                        return ((int)(this[this.tableGET_DETALLE_EOR_TRANSITO.ID_BODEGAColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("El valor de la columna \'ID_BODEGA\' de la tabla \'GET_DETALLE_EOR_TRANSITO\' es DBNu" +
                                "ll.", e);
                    }
                }
                set {
                    this[this.tableGET_DETALLE_EOR_TRANSITO.ID_BODEGAColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string ID_PRODUCTO {
                get {
                    try {
                        return ((string)(this[this.tableGET_DETALLE_EOR_TRANSITO.ID_PRODUCTOColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("El valor de la columna \'ID_PRODUCTO\' de la tabla \'GET_DETALLE_EOR_TRANSITO\' es DB" +
                                "Null.", e);
                    }
                }
                set {
                    this[this.tableGET_DETALLE_EOR_TRANSITO.ID_PRODUCTOColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string NOMBRE {
                get {
                    try {
                        return ((string)(this[this.tableGET_DETALLE_EOR_TRANSITO.NOMBREColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("El valor de la columna \'NOMBRE\' de la tabla \'GET_DETALLE_EOR_TRANSITO\' es DBNull." +
                                "", e);
                    }
                }
                set {
                    this[this.tableGET_DETALLE_EOR_TRANSITO.NOMBREColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string TIPO {
                get {
                    try {
                        return ((string)(this[this.tableGET_DETALLE_EOR_TRANSITO.TIPOColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("El valor de la columna \'TIPO\' de la tabla \'GET_DETALLE_EOR_TRANSITO\' es DBNull.", e);
                    }
                }
                set {
                    this[this.tableGET_DETALLE_EOR_TRANSITO.TIPOColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public decimal CANTIDAD {
                get {
                    try {
                        return ((decimal)(this[this.tableGET_DETALLE_EOR_TRANSITO.CANTIDADColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("El valor de la columna \'CANTIDAD\' de la tabla \'GET_DETALLE_EOR_TRANSITO\' es DBNul" +
                                "l.", e);
                    }
                }
                set {
                    this[this.tableGET_DETALLE_EOR_TRANSITO.CANTIDADColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public decimal COSTO {
                get {
                    try {
                        return ((decimal)(this[this.tableGET_DETALLE_EOR_TRANSITO.COSTOColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("El valor de la columna \'COSTO\' de la tabla \'GET_DETALLE_EOR_TRANSITO\' es DBNull.", e);
                    }
                }
                set {
                    this[this.tableGET_DETALLE_EOR_TRANSITO.COSTOColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public decimal TOTAL {
                get {
                    try {
                        return ((decimal)(this[this.tableGET_DETALLE_EOR_TRANSITO.TOTALColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("El valor de la columna \'TOTAL\' de la tabla \'GET_DETALLE_EOR_TRANSITO\' es DBNull.", e);
                    }
                }
                set {
                    this[this.tableGET_DETALLE_EOR_TRANSITO.TOTALColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public decimal COSTO_IVA {
                get {
                    try {
                        return ((decimal)(this[this.tableGET_DETALLE_EOR_TRANSITO.COSTO_IVAColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("El valor de la columna \'COSTO_IVA\' de la tabla \'GET_DETALLE_EOR_TRANSITO\' es DBNu" +
                                "ll.", e);
                    }
                }
                set {
                    this[this.tableGET_DETALLE_EOR_TRANSITO.COSTO_IVAColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public decimal TOTAL_IVA {
                get {
                    try {
                        return ((decimal)(this[this.tableGET_DETALLE_EOR_TRANSITO.TOTAL_IVAColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("El valor de la columna \'TOTAL_IVA\' de la tabla \'GET_DETALLE_EOR_TRANSITO\' es DBNu" +
                                "ll.", e);
                    }
                }
                set {
                    this[this.tableGET_DETALLE_EOR_TRANSITO.TOTAL_IVAColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public int ID_SECDANIO {
                get {
                    try {
                        return ((int)(this[this.tableGET_DETALLE_EOR_TRANSITO.ID_SECDANIOColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("El valor de la columna \'ID_SECDANIO\' de la tabla \'GET_DETALLE_EOR_TRANSITO\' es DB" +
                                "Null.", e);
                    }
                }
                set {
                    this[this.tableGET_DETALLE_EOR_TRANSITO.ID_SECDANIOColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public int CANTIDADREAL {
                get {
                    try {
                        return ((int)(this[this.tableGET_DETALLE_EOR_TRANSITO.CANTIDADREALColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("El valor de la columna \'CANTIDADREAL\' de la tabla \'GET_DETALLE_EOR_TRANSITO\' es D" +
                                "BNull.", e);
                    }
                }
                set {
                    this[this.tableGET_DETALLE_EOR_TRANSITO.CANTIDADREALColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public decimal COSTOREAL {
                get {
                    try {
                        return ((decimal)(this[this.tableGET_DETALLE_EOR_TRANSITO.COSTOREALColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("El valor de la columna \'COSTOREAL\' de la tabla \'GET_DETALLE_EOR_TRANSITO\' es DBNu" +
                                "ll.", e);
                    }
                }
                set {
                    this[this.tableGET_DETALLE_EOR_TRANSITO.COSTOREALColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public decimal TOTALREAL {
                get {
                    try {
                        return ((decimal)(this[this.tableGET_DETALLE_EOR_TRANSITO.TOTALREALColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("El valor de la columna \'TOTALREAL\' de la tabla \'GET_DETALLE_EOR_TRANSITO\' es DBNu" +
                                "ll.", e);
                    }
                }
                set {
                    this[this.tableGET_DETALLE_EOR_TRANSITO.TOTALREALColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsCOSTOMAOBRANull() {
                return this.IsNull(this.tableGET_DETALLE_EOR_TRANSITO.COSTOMAOBRAColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetCOSTOMAOBRANull() {
                this[this.tableGET_DETALLE_EOR_TRANSITO.COSTOMAOBRAColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsCONTAINERNull() {
                return this.IsNull(this.tableGET_DETALLE_EOR_TRANSITO.CONTAINERColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetCONTAINERNull() {
                this[this.tableGET_DETALLE_EOR_TRANSITO.CONTAINERColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsAPROBADOESTNull() {
                return this.IsNull(this.tableGET_DETALLE_EOR_TRANSITO.APROBADOESTColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetAPROBADOESTNull() {
                this[this.tableGET_DETALLE_EOR_TRANSITO.APROBADOESTColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsAPROBADOMAQNull() {
                return this.IsNull(this.tableGET_DETALLE_EOR_TRANSITO.APROBADOMAQColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetAPROBADOMAQNull() {
                this[this.tableGET_DETALLE_EOR_TRANSITO.APROBADOMAQColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsTOTAL_COSTOHHNull() {
                return this.IsNull(this.tableGET_DETALLE_EOR_TRANSITO.TOTAL_COSTOHHColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetTOTAL_COSTOHHNull() {
                this[this.tableGET_DETALLE_EOR_TRANSITO.TOTAL_COSTOHHColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsCOD_DEPOSITONull() {
                return this.IsNull(this.tableGET_DETALLE_EOR_TRANSITO.COD_DEPOSITOColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetCOD_DEPOSITONull() {
                this[this.tableGET_DETALLE_EOR_TRANSITO.COD_DEPOSITOColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsID_BODEGANull() {
                return this.IsNull(this.tableGET_DETALLE_EOR_TRANSITO.ID_BODEGAColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetID_BODEGANull() {
                this[this.tableGET_DETALLE_EOR_TRANSITO.ID_BODEGAColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsID_PRODUCTONull() {
                return this.IsNull(this.tableGET_DETALLE_EOR_TRANSITO.ID_PRODUCTOColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetID_PRODUCTONull() {
                this[this.tableGET_DETALLE_EOR_TRANSITO.ID_PRODUCTOColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsNOMBRENull() {
                return this.IsNull(this.tableGET_DETALLE_EOR_TRANSITO.NOMBREColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetNOMBRENull() {
                this[this.tableGET_DETALLE_EOR_TRANSITO.NOMBREColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsTIPONull() {
                return this.IsNull(this.tableGET_DETALLE_EOR_TRANSITO.TIPOColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetTIPONull() {
                this[this.tableGET_DETALLE_EOR_TRANSITO.TIPOColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsCANTIDADNull() {
                return this.IsNull(this.tableGET_DETALLE_EOR_TRANSITO.CANTIDADColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetCANTIDADNull() {
                this[this.tableGET_DETALLE_EOR_TRANSITO.CANTIDADColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsCOSTONull() {
                return this.IsNull(this.tableGET_DETALLE_EOR_TRANSITO.COSTOColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetCOSTONull() {
                this[this.tableGET_DETALLE_EOR_TRANSITO.COSTOColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsTOTALNull() {
                return this.IsNull(this.tableGET_DETALLE_EOR_TRANSITO.TOTALColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetTOTALNull() {
                this[this.tableGET_DETALLE_EOR_TRANSITO.TOTALColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsCOSTO_IVANull() {
                return this.IsNull(this.tableGET_DETALLE_EOR_TRANSITO.COSTO_IVAColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetCOSTO_IVANull() {
                this[this.tableGET_DETALLE_EOR_TRANSITO.COSTO_IVAColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsTOTAL_IVANull() {
                return this.IsNull(this.tableGET_DETALLE_EOR_TRANSITO.TOTAL_IVAColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetTOTAL_IVANull() {
                this[this.tableGET_DETALLE_EOR_TRANSITO.TOTAL_IVAColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsID_SECDANIONull() {
                return this.IsNull(this.tableGET_DETALLE_EOR_TRANSITO.ID_SECDANIOColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetID_SECDANIONull() {
                this[this.tableGET_DETALLE_EOR_TRANSITO.ID_SECDANIOColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsCANTIDADREALNull() {
                return this.IsNull(this.tableGET_DETALLE_EOR_TRANSITO.CANTIDADREALColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetCANTIDADREALNull() {
                this[this.tableGET_DETALLE_EOR_TRANSITO.CANTIDADREALColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsCOSTOREALNull() {
                return this.IsNull(this.tableGET_DETALLE_EOR_TRANSITO.COSTOREALColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetCOSTOREALNull() {
                this[this.tableGET_DETALLE_EOR_TRANSITO.COSTOREALColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsTOTALREALNull() {
                return this.IsNull(this.tableGET_DETALLE_EOR_TRANSITO.TOTALREALColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetTOTALREALNull() {
                this[this.tableGET_DETALLE_EOR_TRANSITO.TOTALREALColumn] = global::System.Convert.DBNull;
            }
        }
        
        /// <summary>
        ///Row event argument class
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public class GET_DETALLE_EOR_TRANSITORowChangeEvent : global::System.EventArgs {
            
            private GET_DETALLE_EOR_TRANSITORow eventRow;
            
            private global::System.Data.DataRowAction eventAction;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public GET_DETALLE_EOR_TRANSITORowChangeEvent(GET_DETALLE_EOR_TRANSITORow row, global::System.Data.DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public GET_DETALLE_EOR_TRANSITORow Row {
                get {
                    return this.eventRow;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
    }
}

#pragma warning restore 1591