USE [B1_PRB_ARETINA]
GO

INSERT INTO [dbo].[OCRD]
           ([CardCode]
           ,[CardName]
           ,[CardType]
           ,[GroupCode]
           ,[CmpPrivate]
           ,[Address]
           ,[ZipCode]
           ,[MailAddres]
           ,[MailZipCod]
           ,[Phone1]
           ,[Phone2]
           ,[Fax]
           ,[CntctPrsn]
           ,[Notes]
           ,[Balance]
           ,[ChecksBal]
           ,[DNotesBal]
           ,[OrdersBal]
           ,[GroupNum]
           ,[CreditLine]
           ,[DebtLine]
           ,[Discount]
           ,[VatStatus]
           ,[LicTradNum]
           ,[DdctStatus]
           ,[DdctPrcnt]
           ,[ValidUntil]
           ,[Chrctrstcs]
           ,[ExMatchNum]
           ,[InMatchNum]
           ,[ListNum]
           ,[DNoteBalFC]
           ,[OrderBalFC]
           ,[DNoteBalSy]
           ,[OrderBalSy]
           ,[Transfered]
           ,[BalTrnsfrd]
           ,[IntrstRate]
           ,[Commission]
           ,[CommGrCode]
           ,[Free_Text]
           ,[SlpCode]
           ,[PrevYearAc]
           ,[Currency]
           ,[RateDifAct]
           ,[BalanceSys]
           ,[BalanceFC]
           ,[Protected]
           ,[Cellular]
           ,[AvrageLate]
           ,[City]
           ,[County]
           ,[Country]
           ,[MailCity]
           ,[MailCounty]
           ,[MailCountr]
           ,[E_Mail]
           ,[Picture]
           ,[DflAccount]
           ,[DflBranch]
           ,[BankCode]
           ,[AddID]
           ,[Pager]
           ,[FatherCard]
           ,[CardFName]
           ,[FatherType]
           ,[QryGroup1]
           ,[QryGroup2]
           ,[QryGroup3]
           ,[QryGroup4]
           ,[QryGroup5]
           ,[QryGroup6]
           ,[QryGroup7]
           ,[QryGroup8]
           ,[QryGroup9]
           ,[QryGroup10]
           ,[QryGroup11]
           ,[QryGroup12]
           ,[QryGroup13]
           ,[QryGroup14]
           ,[QryGroup15]
           ,[QryGroup16]
           ,[QryGroup17]
           ,[QryGroup18]
           ,[QryGroup19]
           ,[QryGroup20]
           ,[QryGroup21]
           ,[QryGroup22]
           ,[QryGroup23]
           ,[QryGroup24]
           ,[QryGroup25]
           ,[QryGroup26]
           ,[QryGroup27]
           ,[QryGroup28]
           ,[QryGroup29]
           ,[QryGroup30]
           ,[QryGroup31]
           ,[QryGroup32]
           ,[QryGroup33]
           ,[QryGroup34]
           ,[QryGroup35]
           ,[QryGroup36]
           ,[QryGroup37]
           ,[QryGroup38]
           ,[QryGroup39]
           ,[QryGroup40]
           ,[QryGroup41]
           ,[QryGroup42]
           ,[QryGroup43]
           ,[QryGroup44]
           ,[QryGroup45]
           ,[QryGroup46]
           ,[QryGroup47]
           ,[QryGroup48]
           ,[QryGroup49]
           ,[QryGroup50]
           ,[QryGroup51]
           ,[QryGroup52]
           ,[QryGroup53]
           ,[QryGroup54]
           ,[QryGroup55]
           ,[QryGroup56]
           ,[QryGroup57]
           ,[QryGroup58]
           ,[QryGroup59]
           ,[QryGroup60]
           ,[QryGroup61]
           ,[QryGroup62]
           ,[QryGroup63]
           ,[QryGroup64]
           ,[DdctOffice]
           ,[CreateDate]
           ,[UpdateDate]
           ,[ExportCode]
           ,[DscntObjct]
           ,[DscntRel]
           ,[SPGCounter]
           ,[SPPCounter]
           ,[DdctFileNo]
           ,[SCNCounter]
           ,[MinIntrst]
           ,[DataSource]
           ,[OprCount]
           ,[ExemptNo]
           ,[Priority]
           ,[CreditCard]
           ,[CrCardNum]
           ,[CardValid]
           ,[UserSign]
           ,[LocMth]
           ,[validFor]
           ,[validFrom]
           ,[validTo]
           ,[frozenFor]
           ,[frozenFrom]
           ,[frozenTo]
           ,[sEmployed]
           ,[MTHCounter]
           ,[BNKCounter]
           ,[DdgKey]
           ,[DdtKey]
           ,[ValidComm]
           ,[FrozenComm]
           ,[chainStore]
           ,[DiscInRet]
           ,[State1]
           ,[State2]
           ,[VatGroup]
           ,[LogInstanc]
           ,[ObjType]
           ,[Indicator]
           ,[ShipType]
           ,[DebPayAcct]
           ,[ShipToDef]
           ,[Block]
           ,[MailBlock]
           ,[Password]
           ,[ECVatGroup]
           ,[Deleted]
           ,[IBAN]
           ,[DocEntry]
           ,[FormCode]
           ,[Box1099]
           ,[PymCode]
           ,[BackOrder]
           ,[PartDelivr]
           ,[DunnLevel]
           ,[DunnDate]
           ,[BlockDunn]
           ,[BankCountr]
           ,[CollecAuth]
           ,[DME]
           ,[InstrucKey]
           ,[SinglePaym]
           ,[ISRBillId]
           ,[PaymBlock]
           ,[RefDetails]
           ,[HouseBank]
           ,[OwnerIdNum]
           ,[PyBlckDesc]
           ,[HousBnkCry]
           ,[HousBnkAct]
           ,[HousBnkBrn]
           ,[ProjectCod]
           ,[SysMatchNo]
           ,[VatIdUnCmp]
           ,[AgentCode]
           ,[TolrncDays]
           ,[SelfInvoic]
           ,[DeferrTax]
           ,[LetterNum]
           ,[MaxAmount]
           ,[FromDate]
           ,[ToDate]
           ,[WTLiable]
           ,[CrtfcateNO]
           ,[ExpireDate]
           ,[NINum]
           ,[AccCritria]
           ,[WTCode]
           ,[Equ]
           ,[HldCode]
           ,[ConnBP]
           ,[MltMthNum]
           ,[TypWTReprt]
           ,[VATRegNum]
           ,[RepName]
           ,[Industry]
           ,[Business]
           ,[WTTaxCat]
           ,[IsDomestic]
           ,[IsResident]
           ,[AutoCalBCG]
           ,[OtrCtlAcct]
           ,[AliasName]
           ,[Building]
           ,[MailBuildi]
           ,[BoEPrsnt]
           ,[BoEDiscnt]
           ,[BoEOnClct]
           ,[UnpaidBoE]
           ,[ITWTCode]
           ,[DunTerm]
           ,[ChannlBP]
           ,[DfTcnician]
           ,[Territory]
           ,[BillToDef]
           ,[DpmClear]
           ,[IntrntSite]
           ,[LangCode]
           ,[HousActKey]
           ,[Profession]
           ,[CDPNum]
           ,[DflBankKey]
           ,[BCACode]
		   ,U_TIPO_PROVEEDOR
		   ,U_TIPO_RUC
		   ,U_TIPO_ID)

SELECT
	  convert(nvarchar(15),[CardCode])[CardCode],
	  convert(nvarchar(100),[CardName])[CardName],
      convert(char(1),[CardType])[CardType],
      convert(smallint, [GroupCode]) [GroupCode],
      convert(char(1),[CmpPrivate])[CmpPrivate],
      convert(nvarchar(100),[Address]),
      convert(nvarchar(20),[ZipCode]),
      convert(nvarchar(100),[MailAddres]),
      convert(nvarchar(20),[MailZipCod]),
      convert(nvarchar(20),[Phone1]),
      convert(nvarchar(20),[Phone2]),
      convert(nvarchar(20),[Fax]),
      convert(nvarchar(90),[CntctPrsn]),
      convert(nvarchar(100),[Notes]),
      convert(numeric(19,6),[Balance]),
      convert(numeric(19,6),[ChecksBal]),
      convert(numeric(19,6),[DNotesBal]),
      convert(numeric(19,6),[OrdersBal]),
      convert(smallint,[GroupNum]),
      convert(numeric(19,6),[CreditLine]),
      convert(numeric(19,6),[DebtLine]),
      convert(numeric(19,6),[Discount]),
      convert(char(1),[VatStatus]),
      convert(nvarchar(32),[LicTradNum]),
      convert(char(1),[DdctStatus]),
      convert(numeric(19,6),[DdctPrcnt]),
	  null [ValidUntil],      
      null [Chrctrstcs],
      null [ExMatchNum],
      null [InMatchNum],
      convert(smallint,[ListNum]),
      convert(numeric(19,6),[DNoteBalFC]),
      convert(numeric(19,6),[OrderBalFC]),
      convert(numeric(19,6),[DNoteBalSy]),
      convert(numeric(19,6),[OrderBalSy]),
      convert(char(1),[Transfered]),
      convert(char(1),[BalTrnsfrd]),
      convert(numeric(19,6),[IntrstRate]),
      convert(numeric(19,6),[Commission]),
      convert(smallint,[CommGrCode]),
      convert(ntext,[Free_Text]),
      convert(int,[SlpCode]),
      convert(char(1),[PrevYearAc]),
      convert(nvarchar(3),[Currency]),
      convert(nvarchar(15),[RateDifAct]),
      convert(numeric(19,6),[BalanceSys]),
      convert(numeric(19,6),[BalanceFC]),
      convert(char(1),[Protected]),
      convert(nvarchar(50),[Cellular]),
      null [AvrageLate],
      convert(nvarchar(100),[City]),
      convert(nvarchar(100),[County]),
      convert(nvarchar(3),[Country]),
      convert(nvarchar(100),[MailCity]),
      convert(nvarchar(100),[MailCounty]),
      convert(nvarchar(3),[MailCountr]),
      convert(nvarchar(100),[E_Mail]),
      convert(nvarchar(200),[Picture]),
      convert(nvarchar(50),[DflAccount]),
      convert(nvarchar(50),[DflBranch]),
      convert(nvarchar(30),[BankCode]),
      convert(nvarchar(64),[AddID]),
      convert(nvarchar(30),[Pager]),
      convert(nvarchar(15),[FatherCard]),
      convert(nvarchar(100),[CardFName]),
      convert(char(1),[FatherType]),
      convert(char(1),[QryGroup1]),
      convert(char(1),[QryGroup2]),
      convert(char(1),[QryGroup3]),
      convert(char(1),[QryGroup4]),
      convert(char(1),[QryGroup5]),
      convert(char(1),[QryGroup6]),
      convert(char(1),[QryGroup7]),
      convert(char(1),[QryGroup8]),
      convert(char(1),[QryGroup9]),
      convert(char(1),[QryGroup10]),
      convert(char(1),[QryGroup11]),
      convert(char(1),[QryGroup12]),
      convert(char(1),[QryGroup13]),
      convert(char(1),[QryGroup14]),
      convert(char(1),[QryGroup15]),
      convert(char(1),[QryGroup16]),
      convert(char(1),[QryGroup17]),
      convert(char(1),[QryGroup18]),
      convert(char(1),[QryGroup19]),
      convert(char(1),[QryGroup20]),
      convert(char(1),[QryGroup21]),
      convert(char(1),[QryGroup22]),
      convert(char(1),[QryGroup23]),
      convert(char(1),[QryGroup24]),
      convert(char(1),[QryGroup25]),
      convert(char(1),[QryGroup26]),
      convert(char(1),[QryGroup27]),
      convert(char(1),[QryGroup28]),
      convert(char(1),[QryGroup29]),
      convert(char(1),[QryGroup30]),
      convert(char(1),[QryGroup31]),
      convert(char(1),[QryGroup32]),
      convert(char(1),[QryGroup33]),
      convert(char(1),[QryGroup34]),
      convert(char(1),[QryGroup35]),
      convert(char(1),[QryGroup36]),
      convert(char(1),[QryGroup37]),
      convert(char(1),[QryGroup38]),
      convert(char(1),[QryGroup39]),
      convert(char(1),[QryGroup40]),
      convert(char(1),[QryGroup41]),
      convert(char(1),[QryGroup42]),
      convert(char(1),[QryGroup43]),
      convert(char(1),[QryGroup44]),
      convert(char(1),[QryGroup45]),
      convert(char(1),[QryGroup46]),
      convert(char(1),[QryGroup47]),
      convert(char(1),[QryGroup48]),
      convert(char(1),[QryGroup49]),
      convert(char(1),[QryGroup50]),
      convert(char(1),[QryGroup51]),
      convert(char(1),[QryGroup52]),
      convert(char(1),[QryGroup53]),
      convert(char(1),[QryGroup54]),
      convert(char(1),[QryGroup55]),
      convert(char(1),[QryGroup56]),
      convert(char(1),[QryGroup57]),
      convert(char(1),[QryGroup58]),
      convert(char(1),[QryGroup59]),
      convert(char(1),[QryGroup60]),
      convert(char(1),[QryGroup61]),
      convert(char(1),[QryGroup62]),
      convert(char(1),[QryGroup63]),
      convert(char(1),[QryGroup64]),
      convert(nvarchar(10),[DdctOffice]),
      convert(datetime,[CreateDate]),
      convert(datetime,[UpdateDate]),
      convert(nvarchar(8),[ExportCode]),
      convert(smallint,[DscntObjct]),
      convert(char(1),[DscntRel]),
      convert(smallint,[SPGCounter]),
      convert(int,[SPPCounter]),
      convert(nvarchar(9),[DdctFileNo]),
      null [SCNCounter],
      convert(numeric(19,6),[MinIntrst]),
      convert(char(1),[DataSource]),
      null [OprCount],
      convert(nvarchar(50),[ExemptNo]),
      null [Priority],
      convert(smallint,[CreditCard]),
      convert(nvarchar(64),[CrCardNum]),
      null [CardValid],
      convert(smallint,[UserSign]),
      convert(char(1),[LocMth]),
      convert(char(1),[validFor]),
	  null [validFrom],      
      null [validTo],
      convert(char(1),[frozenFor]),
      null [frozenFrom],
      null [frozenTo],
      convert(char(1),[sEmployed]),
      null [MTHCounter],
      null [BNKCounter],
      convert(int,[DdgKey]),
      convert(int,[DdtKey]),
      convert(nvarchar(30),[ValidComm]),
      convert(nvarchar(30),[FrozenComm]),
      convert(char(1),[chainStore]),
      convert(char(1),[DiscInRet]),
      convert(nvarchar(3),[State1]),
      convert(nvarchar(3),[State2]),
      convert(nvarchar(8),[VatGroup]),
      convert(int,[LogInstanc]),
      convert(nvarchar(20),[ObjType]),
      convert(nvarchar(2),[Indicator]),
      null [ShipType],
      convert(nvarchar(15),[DebPayAcct]),
      convert(nvarchar(50),[ShipToDef]),
      convert(nvarchar(100),[Block]),
      convert(nvarchar(100),[MailBlock]),
      convert(nvarchar(32),[Password]),
      convert(nvarchar(8),[ECVatGroup]),
      convert(char(1),[Deleted]),
      convert(nvarchar(50),[IBAN]),
      convert(int,[DocEntry]),
      null [FormCode],
      convert(nvarchar(20),[Box1099]),
      convert(nvarchar(15),[PymCode]),
      convert(char(1),[BackOrder]),
      convert(char(1),[PartDelivr]),
      convert(int,[DunnLevel]),
      null [DunnDate],
      convert(char(1),[BlockDunn]),
      convert(nvarchar(3),[BankCountr]),
      convert(char(1),[CollecAuth]),
      convert(nvarchar(5),[DME]),
      convert(nvarchar(30),[InstrucKey]),
      convert(char(1),[SinglePaym]),
      convert(nvarchar(9), [ISRBillId]),
      convert(char(1),[PaymBlock]),
      convert(nvarchar(20),[RefDetails]),
      convert(nvarchar(30),[HouseBank]),
      convert(nvarchar(15),[OwnerIdNum]),
      convert(int,[PyBlckDesc]),
      convert(nvarchar(3),[HousBnkCry]),
      convert(nvarchar(50),[HousBnkAct]),
      convert(nvarchar(50),[HousBnkBrn]),
      convert(nvarchar(20),[ProjectCod]),
      convert(int,[SysMatchNo]),
      convert(nvarchar(32),[VatIdUnCmp]),
      convert(nvarchar(32),[AgentCode]),
      null [TolrncDays],
      convert(char(1),[SelfInvoic]),
      convert(char(1),[DeferrTax]),
      convert(nvarchar(20),[LetterNum]),
      convert(numeric(19,6),[MaxAmount]),
      null [FromDate],
      null [ToDate],
      convert(char(1),[WTLiable]),
      convert(nvarchar(20),[CrtfcateNO]),
      null [ExpireDate],
      convert(nvarchar(20),[NINum]),
      convert(char(1),[AccCritria]),
      convert(nvarchar(4),[WTCode]),
      convert(char(1),[Equ]),
      convert(nvarchar(20),[HldCode]),
      convert(nvarchar(15),[ConnBP]),
      null [MltMthNum],
      convert(char(1),[TypWTReprt]),
      convert(nvarchar(32),[VATRegNum]),
      convert(nvarchar(15),[RepName]),
      convert(ntext,[Industry]),
      convert(ntext,[Business]),
      convert(ntext,[WTTaxCat]),
      convert(char(1),[IsDomestic]),
      convert(char(1),[IsResident]),
      convert(char(1),[AutoCalBCG]),
      convert(nvarchar(15),[OtrCtlAcct]),
      convert(ntext,[AliasName]),
      convert(ntext,[Building]),
      convert(ntext,[MailBuildi]),
      convert(nvarchar(15),[BoEPrsnt]),
      convert(nvarchar(15),[BoEDiscnt]),
      convert(nvarchar(15),[BoEOnClct]),
      convert(nvarchar(15),[UnpaidBoE]),
      convert(nvarchar(4),[ITWTCode]),
      convert(nvarchar(25),[DunTerm]),
      convert(nvarchar(15),[ChannlBP]),
      null [DfTcnician],
      null [Territory],
      convert(nvarchar(50),[BillToDef]),
      convert(nvarchar(15),[DpmClear]),
      convert(nvarchar(100),[IntrntSite]),
      convert(int,[LangCode]),
      convert(int,[HousActKey]),
      convert(nvarchar(50),[Profession]),
      null [CDPNum],
      null [DflBankKey],
      convert(nvarchar(3),[BCACode])
	  ,'','',''
  FROM [dbo].[OCRD$]
GO


