//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sigeor.GestionMglServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="GestionMglServiceReference.IGestionMglService")]
    public interface IGestionMglService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionMglService/ObtenerEorEstructuraPorNumero", ReplyAction="http://tempuri.org/IGestionMglService/ObtenerEorEstructuraPorNumeroResponse")]
        string ObtenerEorEstructuraPorNumero(string parametro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionMglService/ObtenerResponsablesReparaciones", ReplyAction="http://tempuri.org/IGestionMglService/ObtenerResponsablesReparacionesResponse")]
        string ObtenerResponsablesReparaciones();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionMglService/ObtenerDepositos", ReplyAction="http://tempuri.org/IGestionMglService/ObtenerDepositosResponse")]
        string ObtenerDepositos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionMglService/ObtenerDepositosPorEstado", ReplyAction="http://tempuri.org/IGestionMglService/ObtenerDepositosPorEstadoResponse")]
        string ObtenerDepositosPorEstado(string estado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionMglService/ObtenerDespositoPorId", ReplyAction="http://tempuri.org/IGestionMglService/ObtenerDespositoPorIdResponse")]
        string ObtenerDespositoPorId(string parametro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionMglService/ObtenerTipoContenedorPorEstado", ReplyAction="http://tempuri.org/IGestionMglService/ObtenerTipoContenedorPorEstadoResponse")]
        string ObtenerTipoContenedorPorEstado(string estado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionMglService/ObtenerTipoContenedorPorTipoEstado", ReplyAction="http://tempuri.org/IGestionMglService/ObtenerTipoContenedorPorTipoEstadoResponse")]
        string ObtenerTipoContenedorPorTipoEstado(string parametroSerializado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionMglService/ObtenerLineas", ReplyAction="http://tempuri.org/IGestionMglService/ObtenerLineasResponse")]
        string ObtenerLineas();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionMglService/ObtenerLineasPorEstado", ReplyAction="http://tempuri.org/IGestionMglService/ObtenerLineasPorEstadoResponse")]
        string ObtenerLineasPorEstado(string estado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionMglService/ObtenerLineaPorCodigo", ReplyAction="http://tempuri.org/IGestionMglService/ObtenerLineaPorCodigoResponse")]
        string ObtenerLineaPorCodigo(string parametro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionMglService/ObtenerProveedores", ReplyAction="http://tempuri.org/IGestionMglService/ObtenerProveedoresResponse")]
        string ObtenerProveedores();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionMglService/ObtenerProveedoresPorEstado", ReplyAction="http://tempuri.org/IGestionMglService/ObtenerProveedoresPorEstadoResponse")]
        string ObtenerProveedoresPorEstado(string estado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionMglService/ObtenerProveedoresPorEstadoPaginado", ReplyAction="http://tempuri.org/IGestionMglService/ObtenerProveedoresPorEstadoPaginadoResponse" +
            "")]
        string ObtenerProveedoresPorEstadoPaginado(out int totalRegistros, bool estado, int pageSize, int pageIndex);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionMglService/ObtenerProveedoresPorCoincidenciaPaginado", ReplyAction="http://tempuri.org/IGestionMglService/ObtenerProveedoresPorCoincidenciaPaginadoRe" +
            "sponse")]
        string ObtenerProveedoresPorCoincidenciaPaginado(out int totalRegistros, string value, bool estado, int pagesize, int pageIndex);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionMglService/ObtenerProveedorPorId", ReplyAction="http://tempuri.org/IGestionMglService/ObtenerProveedorPorIdResponse")]
        string ObtenerProveedorPorId(string parametro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionMglService/InsertarProveedor", ReplyAction="http://tempuri.org/IGestionMglService/InsertarProveedorResponse")]
        void InsertarProveedor(string proveedor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionMglService/ModificarProveedor", ReplyAction="http://tempuri.org/IGestionMglService/ModificarProveedorResponse")]
        void ModificarProveedor(string proveedor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionMglService/EliminarProveedor", ReplyAction="http://tempuri.org/IGestionMglService/EliminarProveedorResponse")]
        void EliminarProveedor(string proveedor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionMglService/ModificarProveedorEstadoMasivamente", ReplyAction="http://tempuri.org/IGestionMglService/ModificarProveedorEstadoMasivamenteResponse" +
            "")]
        void ModificarProveedorEstadoMasivamente(string parametroProveedor);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGestionMglServiceChannel : Sigeor.GestionMglServiceReference.IGestionMglService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GestionMglServiceClient : System.ServiceModel.ClientBase<Sigeor.GestionMglServiceReference.IGestionMglService>, Sigeor.GestionMglServiceReference.IGestionMglService {
        
        public GestionMglServiceClient() {
        }
        
        public GestionMglServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GestionMglServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GestionMglServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GestionMglServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string ObtenerEorEstructuraPorNumero(string parametro) {
            return base.Channel.ObtenerEorEstructuraPorNumero(parametro);
        }
        
        public string ObtenerResponsablesReparaciones() {
            return base.Channel.ObtenerResponsablesReparaciones();
        }
        
        public string ObtenerDepositos() {
            return base.Channel.ObtenerDepositos();
        }
        
        public string ObtenerDepositosPorEstado(string estado) {
            return base.Channel.ObtenerDepositosPorEstado(estado);
        }
        
        public string ObtenerDespositoPorId(string parametro) {
            return base.Channel.ObtenerDespositoPorId(parametro);
        }
        
        public string ObtenerTipoContenedorPorEstado(string estado) {
            return base.Channel.ObtenerTipoContenedorPorEstado(estado);
        }
        
        public string ObtenerTipoContenedorPorTipoEstado(string parametroSerializado) {
            return base.Channel.ObtenerTipoContenedorPorTipoEstado(parametroSerializado);
        }
        
        public string ObtenerLineas() {
            return base.Channel.ObtenerLineas();
        }
        
        public string ObtenerLineasPorEstado(string estado) {
            return base.Channel.ObtenerLineasPorEstado(estado);
        }
        
        public string ObtenerLineaPorCodigo(string parametro) {
            return base.Channel.ObtenerLineaPorCodigo(parametro);
        }
        
        public string ObtenerProveedores() {
            return base.Channel.ObtenerProveedores();
        }
        
        public string ObtenerProveedoresPorEstado(string estado) {
            return base.Channel.ObtenerProveedoresPorEstado(estado);
        }
        
        public string ObtenerProveedoresPorEstadoPaginado(out int totalRegistros, bool estado, int pageSize, int pageIndex) {
            return base.Channel.ObtenerProveedoresPorEstadoPaginado(out totalRegistros, estado, pageSize, pageIndex);
        }
        
        public string ObtenerProveedoresPorCoincidenciaPaginado(out int totalRegistros, string value, bool estado, int pagesize, int pageIndex) {
            return base.Channel.ObtenerProveedoresPorCoincidenciaPaginado(out totalRegistros, value, estado, pagesize, pageIndex);
        }
        
        public string ObtenerProveedorPorId(string parametro) {
            return base.Channel.ObtenerProveedorPorId(parametro);
        }
        
        public void InsertarProveedor(string proveedor) {
            base.Channel.InsertarProveedor(proveedor);
        }
        
        public void ModificarProveedor(string proveedor) {
            base.Channel.ModificarProveedor(proveedor);
        }
        
        public void EliminarProveedor(string proveedor) {
            base.Channel.EliminarProveedor(proveedor);
        }
        
        public void ModificarProveedorEstadoMasivamente(string parametroProveedor) {
            base.Channel.ModificarProveedorEstadoMasivamente(parametroProveedor);
        }
    }
}
