//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sigeor.GestionConfiguracionServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="GestionConfiguracionServiceReference.IConfiguracionService")]
    public interface IConfiguracionService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConfiguracionService/InsertarPerfil", ReplyAction="http://tempuri.org/IConfiguracionService/InsertarPerfilResponse")]
        void InsertarPerfil(string perfil);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConfiguracionService/ModificarPerfil", ReplyAction="http://tempuri.org/IConfiguracionService/ModificarPerfilResponse")]
        void ModificarPerfil(string Perfilerializado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConfiguracionService/ModificarMasivamentePerfiles", ReplyAction="http://tempuri.org/IConfiguracionService/ModificarMasivamentePerfilesResponse")]
        void ModificarMasivamentePerfiles(string parametroSerializado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConfiguracionService/EliminarPerfil", ReplyAction="http://tempuri.org/IConfiguracionService/EliminarPerfilResponse")]
        void EliminarPerfil(string perfil);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConfiguracionService/ObtenerPerfilesPorEstado", ReplyAction="http://tempuri.org/IConfiguracionService/ObtenerPerfilesPorEstadoResponse")]
        string ObtenerPerfilesPorEstado(bool estado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConfiguracionService/ObtenerPerfilesPorEstadoPaginado", ReplyAction="http://tempuri.org/IConfiguracionService/ObtenerPerfilesPorEstadoPaginadoResponse" +
            "")]
        string ObtenerPerfilesPorEstadoPaginado(out int totalRegistros, bool estado, int pageSize, int pageIndex);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConfiguracionService/ObtenerPerfiles", ReplyAction="http://tempuri.org/IConfiguracionService/ObtenerPerfilesResponse")]
        string ObtenerPerfiles();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConfiguracionService/ObtenerPerfilesPaginado", ReplyAction="http://tempuri.org/IConfiguracionService/ObtenerPerfilesPaginadoResponse")]
        string ObtenerPerfilesPaginado(out int totalRegistros, int pageSize, int pageIndex);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConfiguracionService/ObtenerPerfilesPorId", ReplyAction="http://tempuri.org/IConfiguracionService/ObtenerPerfilesPorIdResponse")]
        string ObtenerPerfilesPorId(System.Guid id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConfiguracionService/ObtenerPerfilesPorCoincidencia", ReplyAction="http://tempuri.org/IConfiguracionService/ObtenerPerfilesPorCoincidenciaResponse")]
        string ObtenerPerfilesPorCoincidencia(string value, bool estado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConfiguracionService/ObtenerPerfilesPorCoincidenciaPaginado", ReplyAction="http://tempuri.org/IConfiguracionService/ObtenerPerfilesPorCoincidenciaPaginadoRe" +
            "sponse")]
        string ObtenerPerfilesPorCoincidenciaPaginado(out int totalRegistros, string value, bool estado, int pageSize, int pageIndex);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConfiguracionService/ObtenerPerfilesPorCodigo", ReplyAction="http://tempuri.org/IConfiguracionService/ObtenerPerfilesPorCodigoResponse")]
        string ObtenerPerfilesPorCodigo(string codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConfiguracionService/ObtenerPerfilEstructuraPorPerfil", ReplyAction="http://tempuri.org/IConfiguracionService/ObtenerPerfilEstructuraPorPerfilResponse" +
            "")]
        string ObtenerPerfilEstructuraPorPerfil(string perfil);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConfiguracionService/InsertarUsuario", ReplyAction="http://tempuri.org/IConfiguracionService/InsertarUsuarioResponse")]
        void InsertarUsuario(string Usuarioerializado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConfiguracionService/ModificarUsuario", ReplyAction="http://tempuri.org/IConfiguracionService/ModificarUsuarioResponse")]
        void ModificarUsuario(string Usuarioerializado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConfiguracionService/EliminarUsuario", ReplyAction="http://tempuri.org/IConfiguracionService/EliminarUsuarioResponse")]
        void EliminarUsuario(string usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConfiguracionService/ObtenerUsuarioPorEstado", ReplyAction="http://tempuri.org/IConfiguracionService/ObtenerUsuarioPorEstadoResponse")]
        string ObtenerUsuarioPorEstado(bool estado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConfiguracionService/ObtenerUsuario", ReplyAction="http://tempuri.org/IConfiguracionService/ObtenerUsuarioResponse")]
        string ObtenerUsuario();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConfiguracionService/ObtenerUsuarioPorCedula", ReplyAction="http://tempuri.org/IConfiguracionService/ObtenerUsuarioPorCedulaResponse")]
        string ObtenerUsuarioPorCedula(string cedula);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConfiguracionService/ObtenerUsuarioPorCorreo", ReplyAction="http://tempuri.org/IConfiguracionService/ObtenerUsuarioPorCorreoResponse")]
        string ObtenerUsuarioPorCorreo(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConfiguracionService/ObtenerUsuarioPorCoincidencia", ReplyAction="http://tempuri.org/IConfiguracionService/ObtenerUsuarioPorCoincidenciaResponse")]
        string ObtenerUsuarioPorCoincidencia(string value, bool estado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConfiguracionService/ModificarUsuarioMasivamente", ReplyAction="http://tempuri.org/IConfiguracionService/ModificarUsuarioMasivamenteResponse")]
        void ModificarUsuarioMasivamente(string value, bool estado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConfiguracionService/ObtenerUsuarioPorEstadoPaginado", ReplyAction="http://tempuri.org/IConfiguracionService/ObtenerUsuarioPorEstadoPaginadoResponse")]
        string ObtenerUsuarioPorEstadoPaginado(out int totalRegistros, bool estado, int pageSize, int pageIndex);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConfiguracionService/ObtenerUsuarioPaginado", ReplyAction="http://tempuri.org/IConfiguracionService/ObtenerUsuarioPaginadoResponse")]
        string ObtenerUsuarioPaginado(out int totalRegistros, int pageSize, int pageIndex);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConfiguracionService/ObtenerUsuarioPorCoincidenciaPaginado", ReplyAction="http://tempuri.org/IConfiguracionService/ObtenerUsuarioPorCoincidenciaPaginadoRes" +
            "ponse")]
        string ObtenerUsuarioPorCoincidenciaPaginado(out int totalRegistros, string value, bool estado, int pageSize, int pageIndex);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConfiguracionService/InsertarUsuarioPerfil", ReplyAction="http://tempuri.org/IConfiguracionService/InsertarUsuarioPerfilResponse")]
        void InsertarUsuarioPerfil(string usuarioPerfil);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConfiguracionService/ModificarUsuarioPerfil", ReplyAction="http://tempuri.org/IConfiguracionService/ModificarUsuarioPerfilResponse")]
        void ModificarUsuarioPerfil(string usuarioPerfilerializado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConfiguracionService/EliminarUsuarioPerfil", ReplyAction="http://tempuri.org/IConfiguracionService/EliminarUsuarioPerfilResponse")]
        void EliminarUsuarioPerfil(string usuarioPerfilerializado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConfiguracionService/ObtenerUsuarioPerfilPorCedula", ReplyAction="http://tempuri.org/IConfiguracionService/ObtenerUsuarioPerfilPorCedulaResponse")]
        string ObtenerUsuarioPerfilPorCedula(string cedula);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConfiguracionService/InsertarEstructura", ReplyAction="http://tempuri.org/IConfiguracionService/InsertarEstructuraResponse")]
        void InsertarEstructura(string Estructuraerializada);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConfiguracionService/ModificarEstructura", ReplyAction="http://tempuri.org/IConfiguracionService/ModificarEstructuraResponse")]
        void ModificarEstructura(string Estructuraerializada);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConfiguracionService/EliminarEstructura", ReplyAction="http://tempuri.org/IConfiguracionService/EliminarEstructuraResponse")]
        void EliminarEstructura(string Estructuraerializada);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConfiguracionService/ObtenerEstructuraPorEstado", ReplyAction="http://tempuri.org/IConfiguracionService/ObtenerEstructuraPorEstadoResponse")]
        string ObtenerEstructuraPorEstado(bool estado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConfiguracionService/ObtenerEstructuraPorId", ReplyAction="http://tempuri.org/IConfiguracionService/ObtenerEstructuraPorIdResponse")]
        string ObtenerEstructuraPorId(string idSerializado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConfiguracionService/ObtenerEstructura", ReplyAction="http://tempuri.org/IConfiguracionService/ObtenerEstructuraResponse")]
        string ObtenerEstructura(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConfiguracionService/ObtenerTituloPorPagina", ReplyAction="http://tempuri.org/IConfiguracionService/ObtenerTituloPorPaginaResponse")]
        string ObtenerTituloPorPagina(string pagina);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConfiguracionService/InsertarEstructuraPerfil", ReplyAction="http://tempuri.org/IConfiguracionService/InsertarEstructuraPerfilResponse")]
        void InsertarEstructuraPerfil(string EstructuraPerfilerializada);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConfiguracionService/ModificarEstructuraPerfil", ReplyAction="http://tempuri.org/IConfiguracionService/ModificarEstructuraPerfilResponse")]
        void ModificarEstructuraPerfil(string EstructuraPerfilerializada);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConfiguracionService/EliminarEstructuraPerfil", ReplyAction="http://tempuri.org/IConfiguracionService/EliminarEstructuraPerfilResponse")]
        void EliminarEstructuraPerfil(string EstructuraPerfilerializada);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConfiguracionService/ObtenerEstructuraPerfilesPorIdPerfil", ReplyAction="http://tempuri.org/IConfiguracionService/ObtenerEstructuraPerfilesPorIdPerfilResp" +
            "onse")]
        string ObtenerEstructuraPerfilesPorIdPerfil(string idSerializado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConfiguracionService/ObtenerEstructuraPerfilesPorIdEstructura" +
            "", ReplyAction="http://tempuri.org/IConfiguracionService/ObtenerEstructuraPerfilesPorIdEstructura" +
            "Response")]
        string ObtenerEstructuraPerfilesPorIdEstructura(string idSerializado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConfiguracionService/ObtenerEstructuraPerfilesPorEstado", ReplyAction="http://tempuri.org/IConfiguracionService/ObtenerEstructuraPerfilesPorEstadoRespon" +
            "se")]
        string ObtenerEstructuraPerfilesPorEstado(bool estado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConfiguracionService/ObtenerEstructuraPerfilesPorCoincidencia" +
            "", ReplyAction="http://tempuri.org/IConfiguracionService/ObtenerEstructuraPerfilesPorCoincidencia" +
            "Response")]
        string ObtenerEstructuraPerfilesPorCoincidencia(string value, bool estado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConfiguracionService/ModificarMasivamentePerfilEstructura", ReplyAction="http://tempuri.org/IConfiguracionService/ModificarMasivamentePerfilEstructuraResp" +
            "onse")]
        void ModificarMasivamentePerfilEstructura(string value, bool estado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConfiguracionService/ObtenerPerfilEstructuraPorEstadoPaginado" +
            "", ReplyAction="http://tempuri.org/IConfiguracionService/ObtenerPerfilEstructuraPorEstadoPaginado" +
            "Response")]
        string ObtenerPerfilEstructuraPorEstadoPaginado(out int totalRegistros, bool estado, int pageSize, int pageIndex);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConfiguracionService/ObtenerPerfilEstructuraPaginado", ReplyAction="http://tempuri.org/IConfiguracionService/ObtenerPerfilEstructuraPaginadoResponse")]
        string ObtenerPerfilEstructuraPaginado(out int totalRegistros, int pageSize, int pageIndex);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConfiguracionService/ObtenerPerfilEstructuraPorCoincidenciaPa" +
            "ginado", ReplyAction="http://tempuri.org/IConfiguracionService/ObtenerPerfilEstructuraPorCoincidenciaPa" +
            "ginadoResponse")]
        string ObtenerPerfilEstructuraPorCoincidenciaPaginado(out int totalRegistros, string value, bool estado, int pageSize, int pageIndex);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConfiguracionService/ObtenerPerfilPorCedula", ReplyAction="http://tempuri.org/IConfiguracionService/ObtenerPerfilPorCedulaResponse")]
        string ObtenerPerfilPorCedula(string cedula);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConfiguracionService/ObtenerAuditoria", ReplyAction="http://tempuri.org/IConfiguracionService/ObtenerAuditoriaResponse")]
        string ObtenerAuditoria();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConfiguracionService/ObtenerAuditoriaPorCoincidencia", ReplyAction="http://tempuri.org/IConfiguracionService/ObtenerAuditoriaPorCoincidenciaResponse")]
        string ObtenerAuditoriaPorCoincidencia(string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConfiguracionService/ObtenerAuditoriaPorCoincidenciaPaginado", ReplyAction="http://tempuri.org/IConfiguracionService/ObtenerAuditoriaPorCoincidenciaPaginadoR" +
            "esponse")]
        string ObtenerAuditoriaPorCoincidenciaPaginado(out int totalRegistros, string value, int pagesize, int pageIndex);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConfiguracionService/InsertarAuditoria", ReplyAction="http://tempuri.org/IConfiguracionService/InsertarAuditoriaResponse")]
        void InsertarAuditoria(string Auditoriaerializado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConfiguracionService/Insertar", ReplyAction="http://tempuri.org/IConfiguracionService/InsertarResponse")]
        void Insertar(string documentoSerializado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConfiguracionService/Modificar", ReplyAction="http://tempuri.org/IConfiguracionService/ModificarResponse")]
        void Modificar(string documentoSerializado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConfiguracionService/Eliminar", ReplyAction="http://tempuri.org/IConfiguracionService/EliminarResponse")]
        void Eliminar(string documentoSerializado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConfiguracionService/ObtenerDoumentos", ReplyAction="http://tempuri.org/IConfiguracionService/ObtenerDoumentosResponse")]
        string ObtenerDoumentos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConfiguracionService/ObtenerDoumentosPaginado", ReplyAction="http://tempuri.org/IConfiguracionService/ObtenerDoumentosPaginadoResponse")]
        string ObtenerDoumentosPaginado(out int totalRegistros, int pageSize, int pageIndex);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConfiguracionService/ObtenerDocumentosPorCoincidencia", ReplyAction="http://tempuri.org/IConfiguracionService/ObtenerDocumentosPorCoincidenciaResponse" +
            "")]
        string ObtenerDocumentosPorCoincidencia(string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConfiguracionService/ObtenerDocumentosPorCoincidenciaPaginado" +
            "", ReplyAction="http://tempuri.org/IConfiguracionService/ObtenerDocumentosPorCoincidenciaPaginado" +
            "Response")]
        string ObtenerDocumentosPorCoincidenciaPaginado(out int totalRegistros, string value, int pageSize, int pageIndex);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConfiguracionService/ObtenerDocumentosPorId", ReplyAction="http://tempuri.org/IConfiguracionService/ObtenerDocumentosPorIdResponse")]
        string ObtenerDocumentosPorId(string idSerializado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConfiguracionService/InsertarConfiguracionEmail", ReplyAction="http://tempuri.org/IConfiguracionService/InsertarConfiguracionEmailResponse")]
        void InsertarConfiguracionEmail(string Emailerializado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConfiguracionService/ObtenerConfiguracionEmail", ReplyAction="http://tempuri.org/IConfiguracionService/ObtenerConfiguracionEmailResponse")]
        string ObtenerConfiguracionEmail();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConfiguracionService/ObtenerPaginadeInicioPorCedula", ReplyAction="http://tempuri.org/IConfiguracionService/ObtenerPaginadeInicioPorCedulaResponse")]
        string ObtenerPaginadeInicioPorCedula(string cedula);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConfiguracionService/ObtenerUrlPorId", ReplyAction="http://tempuri.org/IConfiguracionService/ObtenerUrlPorIdResponse")]
        string ObtenerUrlPorId(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConfiguracionService/InsertarPolitica", ReplyAction="http://tempuri.org/IConfiguracionService/InsertarPoliticaResponse")]
        void InsertarPolitica(string politicaSerializada);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConfiguracionService/ModificarPolitica", ReplyAction="http://tempuri.org/IConfiguracionService/ModificarPoliticaResponse")]
        void ModificarPolitica(string politicaSerializada);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConfiguracionService/ObtenerPoliticaPorcodigo", ReplyAction="http://tempuri.org/IConfiguracionService/ObtenerPoliticaPorcodigoResponse")]
        string ObtenerPoliticaPorcodigo(string parametroSerializado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConfiguracionService/ObtenerPoliticaPorGrupo", ReplyAction="http://tempuri.org/IConfiguracionService/ObtenerPoliticaPorGrupoResponse")]
        string ObtenerPoliticaPorGrupo(string parametroSerializado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConfiguracionService/ModificarAlertaReparacion", ReplyAction="http://tempuri.org/IConfiguracionService/ModificarAlertaReparacionResponse")]
        void ModificarAlertaReparacion(string alertaReparacionSerializada);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConfiguracionService/ObtenerAlertaReparacion", ReplyAction="http://tempuri.org/IConfiguracionService/ObtenerAlertaReparacionResponse")]
        string ObtenerAlertaReparacion(string idAlertaReparacion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConfiguracionService/ObtenerAlertasReparacionPorEstadoPaginad" +
            "o", ReplyAction="http://tempuri.org/IConfiguracionService/ObtenerAlertasReparacionPorEstadoPaginad" +
            "oResponse")]
        string ObtenerAlertasReparacionPorEstadoPaginado(out int totalRegistros, bool estado, int pagesize, int pageIndex);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConfiguracionService/ObtenerAlertasReparacionPorEstado", ReplyAction="http://tempuri.org/IConfiguracionService/ObtenerAlertasReparacionPorEstadoRespons" +
            "e")]
        string ObtenerAlertasReparacionPorEstado(bool estado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConfiguracionService/ObtenerResumenAlertasReparacion", ReplyAction="http://tempuri.org/IConfiguracionService/ObtenerResumenAlertasReparacionResponse")]
        string ObtenerResumenAlertasReparacion();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConfiguracionService/ObtenerAlertasReparacionPorCoincidenciaP" +
            "aginado", ReplyAction="http://tempuri.org/IConfiguracionService/ObtenerAlertasReparacionPorCoincidenciaP" +
            "aginadoResponse")]
        string ObtenerAlertasReparacionPorCoincidenciaPaginado(out int totalRegistros, string value, bool estado, int pageSize, int pageIndex);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConfiguracionService/ObtenerAlertasReparacionPorCoincidencia", ReplyAction="http://tempuri.org/IConfiguracionService/ObtenerAlertasReparacionPorCoincidenciaR" +
            "esponse")]
        string ObtenerAlertasReparacionPorCoincidencia(string value, bool estado);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IConfiguracionServiceChannel : Sigeor.GestionConfiguracionServiceReference.IConfiguracionService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ConfiguracionServiceClient : System.ServiceModel.ClientBase<Sigeor.GestionConfiguracionServiceReference.IConfiguracionService>, Sigeor.GestionConfiguracionServiceReference.IConfiguracionService {
        
        public ConfiguracionServiceClient() {
        }
        
        public ConfiguracionServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ConfiguracionServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConfiguracionServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConfiguracionServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void InsertarPerfil(string perfil) {
            base.Channel.InsertarPerfil(perfil);
        }
        
        public void ModificarPerfil(string Perfilerializado) {
            base.Channel.ModificarPerfil(Perfilerializado);
        }
        
        public void ModificarMasivamentePerfiles(string parametroSerializado) {
            base.Channel.ModificarMasivamentePerfiles(parametroSerializado);
        }
        
        public void EliminarPerfil(string perfil) {
            base.Channel.EliminarPerfil(perfil);
        }
        
        public string ObtenerPerfilesPorEstado(bool estado) {
            return base.Channel.ObtenerPerfilesPorEstado(estado);
        }
        
        public string ObtenerPerfilesPorEstadoPaginado(out int totalRegistros, bool estado, int pageSize, int pageIndex) {
            return base.Channel.ObtenerPerfilesPorEstadoPaginado(out totalRegistros, estado, pageSize, pageIndex);
        }
        
        public string ObtenerPerfiles() {
            return base.Channel.ObtenerPerfiles();
        }
        
        public string ObtenerPerfilesPaginado(out int totalRegistros, int pageSize, int pageIndex) {
            return base.Channel.ObtenerPerfilesPaginado(out totalRegistros, pageSize, pageIndex);
        }
        
        public string ObtenerPerfilesPorId(System.Guid id) {
            return base.Channel.ObtenerPerfilesPorId(id);
        }
        
        public string ObtenerPerfilesPorCoincidencia(string value, bool estado) {
            return base.Channel.ObtenerPerfilesPorCoincidencia(value, estado);
        }
        
        public string ObtenerPerfilesPorCoincidenciaPaginado(out int totalRegistros, string value, bool estado, int pageSize, int pageIndex) {
            return base.Channel.ObtenerPerfilesPorCoincidenciaPaginado(out totalRegistros, value, estado, pageSize, pageIndex);
        }
        
        public string ObtenerPerfilesPorCodigo(string codigo) {
            return base.Channel.ObtenerPerfilesPorCodigo(codigo);
        }
        
        public string ObtenerPerfilEstructuraPorPerfil(string perfil) {
            return base.Channel.ObtenerPerfilEstructuraPorPerfil(perfil);
        }
        
        public void InsertarUsuario(string Usuarioerializado) {
            base.Channel.InsertarUsuario(Usuarioerializado);
        }
        
        public void ModificarUsuario(string Usuarioerializado) {
            base.Channel.ModificarUsuario(Usuarioerializado);
        }
        
        public void EliminarUsuario(string usuario) {
            base.Channel.EliminarUsuario(usuario);
        }
        
        public string ObtenerUsuarioPorEstado(bool estado) {
            return base.Channel.ObtenerUsuarioPorEstado(estado);
        }
        
        public string ObtenerUsuario() {
            return base.Channel.ObtenerUsuario();
        }
        
        public string ObtenerUsuarioPorCedula(string cedula) {
            return base.Channel.ObtenerUsuarioPorCedula(cedula);
        }
        
        public string ObtenerUsuarioPorCorreo(string email) {
            return base.Channel.ObtenerUsuarioPorCorreo(email);
        }
        
        public string ObtenerUsuarioPorCoincidencia(string value, bool estado) {
            return base.Channel.ObtenerUsuarioPorCoincidencia(value, estado);
        }
        
        public void ModificarUsuarioMasivamente(string value, bool estado) {
            base.Channel.ModificarUsuarioMasivamente(value, estado);
        }
        
        public string ObtenerUsuarioPorEstadoPaginado(out int totalRegistros, bool estado, int pageSize, int pageIndex) {
            return base.Channel.ObtenerUsuarioPorEstadoPaginado(out totalRegistros, estado, pageSize, pageIndex);
        }
        
        public string ObtenerUsuarioPaginado(out int totalRegistros, int pageSize, int pageIndex) {
            return base.Channel.ObtenerUsuarioPaginado(out totalRegistros, pageSize, pageIndex);
        }
        
        public string ObtenerUsuarioPorCoincidenciaPaginado(out int totalRegistros, string value, bool estado, int pageSize, int pageIndex) {
            return base.Channel.ObtenerUsuarioPorCoincidenciaPaginado(out totalRegistros, value, estado, pageSize, pageIndex);
        }
        
        public void InsertarUsuarioPerfil(string usuarioPerfil) {
            base.Channel.InsertarUsuarioPerfil(usuarioPerfil);
        }
        
        public void ModificarUsuarioPerfil(string usuarioPerfilerializado) {
            base.Channel.ModificarUsuarioPerfil(usuarioPerfilerializado);
        }
        
        public void EliminarUsuarioPerfil(string usuarioPerfilerializado) {
            base.Channel.EliminarUsuarioPerfil(usuarioPerfilerializado);
        }
        
        public string ObtenerUsuarioPerfilPorCedula(string cedula) {
            return base.Channel.ObtenerUsuarioPerfilPorCedula(cedula);
        }
        
        public void InsertarEstructura(string Estructuraerializada) {
            base.Channel.InsertarEstructura(Estructuraerializada);
        }
        
        public void ModificarEstructura(string Estructuraerializada) {
            base.Channel.ModificarEstructura(Estructuraerializada);
        }
        
        public void EliminarEstructura(string Estructuraerializada) {
            base.Channel.EliminarEstructura(Estructuraerializada);
        }
        
        public string ObtenerEstructuraPorEstado(bool estado) {
            return base.Channel.ObtenerEstructuraPorEstado(estado);
        }
        
        public string ObtenerEstructuraPorId(string idSerializado) {
            return base.Channel.ObtenerEstructuraPorId(idSerializado);
        }
        
        public string ObtenerEstructura(string id) {
            return base.Channel.ObtenerEstructura(id);
        }
        
        public string ObtenerTituloPorPagina(string pagina) {
            return base.Channel.ObtenerTituloPorPagina(pagina);
        }
        
        public void InsertarEstructuraPerfil(string EstructuraPerfilerializada) {
            base.Channel.InsertarEstructuraPerfil(EstructuraPerfilerializada);
        }
        
        public void ModificarEstructuraPerfil(string EstructuraPerfilerializada) {
            base.Channel.ModificarEstructuraPerfil(EstructuraPerfilerializada);
        }
        
        public void EliminarEstructuraPerfil(string EstructuraPerfilerializada) {
            base.Channel.EliminarEstructuraPerfil(EstructuraPerfilerializada);
        }
        
        public string ObtenerEstructuraPerfilesPorIdPerfil(string idSerializado) {
            return base.Channel.ObtenerEstructuraPerfilesPorIdPerfil(idSerializado);
        }
        
        public string ObtenerEstructuraPerfilesPorIdEstructura(string idSerializado) {
            return base.Channel.ObtenerEstructuraPerfilesPorIdEstructura(idSerializado);
        }
        
        public string ObtenerEstructuraPerfilesPorEstado(bool estado) {
            return base.Channel.ObtenerEstructuraPerfilesPorEstado(estado);
        }
        
        public string ObtenerEstructuraPerfilesPorCoincidencia(string value, bool estado) {
            return base.Channel.ObtenerEstructuraPerfilesPorCoincidencia(value, estado);
        }
        
        public void ModificarMasivamentePerfilEstructura(string value, bool estado) {
            base.Channel.ModificarMasivamentePerfilEstructura(value, estado);
        }
        
        public string ObtenerPerfilEstructuraPorEstadoPaginado(out int totalRegistros, bool estado, int pageSize, int pageIndex) {
            return base.Channel.ObtenerPerfilEstructuraPorEstadoPaginado(out totalRegistros, estado, pageSize, pageIndex);
        }
        
        public string ObtenerPerfilEstructuraPaginado(out int totalRegistros, int pageSize, int pageIndex) {
            return base.Channel.ObtenerPerfilEstructuraPaginado(out totalRegistros, pageSize, pageIndex);
        }
        
        public string ObtenerPerfilEstructuraPorCoincidenciaPaginado(out int totalRegistros, string value, bool estado, int pageSize, int pageIndex) {
            return base.Channel.ObtenerPerfilEstructuraPorCoincidenciaPaginado(out totalRegistros, value, estado, pageSize, pageIndex);
        }
        
        public string ObtenerPerfilPorCedula(string cedula) {
            return base.Channel.ObtenerPerfilPorCedula(cedula);
        }
        
        public string ObtenerAuditoria() {
            return base.Channel.ObtenerAuditoria();
        }
        
        public string ObtenerAuditoriaPorCoincidencia(string value) {
            return base.Channel.ObtenerAuditoriaPorCoincidencia(value);
        }
        
        public string ObtenerAuditoriaPorCoincidenciaPaginado(out int totalRegistros, string value, int pagesize, int pageIndex) {
            return base.Channel.ObtenerAuditoriaPorCoincidenciaPaginado(out totalRegistros, value, pagesize, pageIndex);
        }
        
        public void InsertarAuditoria(string Auditoriaerializado) {
            base.Channel.InsertarAuditoria(Auditoriaerializado);
        }
        
        public void Insertar(string documentoSerializado) {
            base.Channel.Insertar(documentoSerializado);
        }
        
        public void Modificar(string documentoSerializado) {
            base.Channel.Modificar(documentoSerializado);
        }
        
        public void Eliminar(string documentoSerializado) {
            base.Channel.Eliminar(documentoSerializado);
        }
        
        public string ObtenerDoumentos() {
            return base.Channel.ObtenerDoumentos();
        }
        
        public string ObtenerDoumentosPaginado(out int totalRegistros, int pageSize, int pageIndex) {
            return base.Channel.ObtenerDoumentosPaginado(out totalRegistros, pageSize, pageIndex);
        }
        
        public string ObtenerDocumentosPorCoincidencia(string value) {
            return base.Channel.ObtenerDocumentosPorCoincidencia(value);
        }
        
        public string ObtenerDocumentosPorCoincidenciaPaginado(out int totalRegistros, string value, int pageSize, int pageIndex) {
            return base.Channel.ObtenerDocumentosPorCoincidenciaPaginado(out totalRegistros, value, pageSize, pageIndex);
        }
        
        public string ObtenerDocumentosPorId(string idSerializado) {
            return base.Channel.ObtenerDocumentosPorId(idSerializado);
        }
        
        public void InsertarConfiguracionEmail(string Emailerializado) {
            base.Channel.InsertarConfiguracionEmail(Emailerializado);
        }
        
        public string ObtenerConfiguracionEmail() {
            return base.Channel.ObtenerConfiguracionEmail();
        }
        
        public string ObtenerPaginadeInicioPorCedula(string cedula) {
            return base.Channel.ObtenerPaginadeInicioPorCedula(cedula);
        }
        
        public string ObtenerUrlPorId(string id) {
            return base.Channel.ObtenerUrlPorId(id);
        }
        
        public void InsertarPolitica(string politicaSerializada) {
            base.Channel.InsertarPolitica(politicaSerializada);
        }
        
        public void ModificarPolitica(string politicaSerializada) {
            base.Channel.ModificarPolitica(politicaSerializada);
        }
        
        public string ObtenerPoliticaPorcodigo(string parametroSerializado) {
            return base.Channel.ObtenerPoliticaPorcodigo(parametroSerializado);
        }
        
        public string ObtenerPoliticaPorGrupo(string parametroSerializado) {
            return base.Channel.ObtenerPoliticaPorGrupo(parametroSerializado);
        }
        
        public void ModificarAlertaReparacion(string alertaReparacionSerializada) {
            base.Channel.ModificarAlertaReparacion(alertaReparacionSerializada);
        }
        
        public string ObtenerAlertaReparacion(string idAlertaReparacion) {
            return base.Channel.ObtenerAlertaReparacion(idAlertaReparacion);
        }
        
        public string ObtenerAlertasReparacionPorEstadoPaginado(out int totalRegistros, bool estado, int pagesize, int pageIndex) {
            return base.Channel.ObtenerAlertasReparacionPorEstadoPaginado(out totalRegistros, estado, pagesize, pageIndex);
        }
        
        public string ObtenerAlertasReparacionPorEstado(bool estado) {
            return base.Channel.ObtenerAlertasReparacionPorEstado(estado);
        }
        
        public string ObtenerResumenAlertasReparacion() {
            return base.Channel.ObtenerResumenAlertasReparacion();
        }
        
        public string ObtenerAlertasReparacionPorCoincidenciaPaginado(out int totalRegistros, string value, bool estado, int pageSize, int pageIndex) {
            return base.Channel.ObtenerAlertasReparacionPorCoincidenciaPaginado(out totalRegistros, value, estado, pageSize, pageIndex);
        }
        
        public string ObtenerAlertasReparacionPorCoincidencia(string value, bool estado) {
            return base.Channel.ObtenerAlertasReparacionPorCoincidencia(value, estado);
        }
    }
}
