//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sigeor.GestionAutenticacionServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StructuralObject", Namespace="http://schemas.datacontract.org/2004/07/System.Data.Objects.DataClasses", IsReference=true)]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Sigeor.GestionAutenticacionServiceReference.EntityObject))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PersistenciaSigeor.CoordenadasEkey))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PersistenciaSigeor.Usuario))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PersistenciaSigeor.UsuarioPerfil))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PersistenciaSigeor.Perfil))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PersistenciaSigeor.EstructuraPerfil))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PersistenciaSigeor.Estructura))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PersistenciaSigeor.EKey))]
    public partial class StructuralObject : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityObject", Namespace="http://schemas.datacontract.org/2004/07/System.Data.Objects.DataClasses", IsReference=true)]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PersistenciaSigeor.CoordenadasEkey))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PersistenciaSigeor.Usuario))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PersistenciaSigeor.UsuarioPerfil))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PersistenciaSigeor.Perfil))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PersistenciaSigeor.EstructuraPerfil))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PersistenciaSigeor.Estructura))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PersistenciaSigeor.EKey))]
    public partial class EntityObject : Sigeor.GestionAutenticacionServiceReference.StructuralObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Sigeor.GestionAutenticacionServiceReference.EntityKey EntityKeyField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Sigeor.GestionAutenticacionServiceReference.EntityKey EntityKey {
            get {
                return this.EntityKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.EntityKeyField, value) != true)) {
                    this.EntityKeyField = value;
                    this.RaisePropertyChanged("EntityKey");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityKey", Namespace="http://schemas.datacontract.org/2004/07/System.Data", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class EntityKey : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EntityContainerNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<Sigeor.GestionAutenticacionServiceReference.EntityKeyMember> EntityKeyValuesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EntitySetNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EntityContainerName {
            get {
                return this.EntityContainerNameField;
            }
            set {
                if ((object.ReferenceEquals(this.EntityContainerNameField, value) != true)) {
                    this.EntityContainerNameField = value;
                    this.RaisePropertyChanged("EntityContainerName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<Sigeor.GestionAutenticacionServiceReference.EntityKeyMember> EntityKeyValues {
            get {
                return this.EntityKeyValuesField;
            }
            set {
                if ((object.ReferenceEquals(this.EntityKeyValuesField, value) != true)) {
                    this.EntityKeyValuesField = value;
                    this.RaisePropertyChanged("EntityKeyValues");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EntitySetName {
            get {
                return this.EntitySetNameField;
            }
            set {
                if ((object.ReferenceEquals(this.EntitySetNameField, value) != true)) {
                    this.EntitySetNameField = value;
                    this.RaisePropertyChanged("EntitySetName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityKeyMember", Namespace="http://schemas.datacontract.org/2004/07/System.Data")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Sigeor.GestionAutenticacionServiceReference.EntityObject))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Sigeor.GestionAutenticacionServiceReference.StructuralObject))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Sigeor.GestionAutenticacionServiceReference.EntityReferenceOfEKeyVQpfUyxC))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Sigeor.GestionAutenticacionServiceReference.EntityReference))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Sigeor.GestionAutenticacionServiceReference.RelatedEnd))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Sigeor.GestionAutenticacionServiceReference.EntityReferenceOfEstructuraVQpfUyxC))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Sigeor.GestionAutenticacionServiceReference.EntityReferenceOfPerfilVQpfUyxC))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Sigeor.GestionAutenticacionServiceReference.EntityReferenceOfUsuarioVQpfUyxC))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PersistenciaSigeor.EKey))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.List<PersistenciaSigeor.CoordenadasEkey>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PersistenciaSigeor.CoordenadasEkey))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PersistenciaSigeor.Usuario))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.List<PersistenciaSigeor.EKey>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.List<PersistenciaSigeor.UsuarioPerfil>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PersistenciaSigeor.UsuarioPerfil))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PersistenciaSigeor.Perfil))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.List<PersistenciaSigeor.EstructuraPerfil>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PersistenciaSigeor.EstructuraPerfil))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PersistenciaSigeor.Estructura))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Sigeor.GestionAutenticacionServiceReference.EntityKey))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.List<Sigeor.GestionAutenticacionServiceReference.EntityKeyMember>))]
    public partial class EntityKeyMember : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private object ValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Key {
            get {
                return this.KeyField;
            }
            set {
                if ((object.ReferenceEquals(this.KeyField, value) != true)) {
                    this.KeyField = value;
                    this.RaisePropertyChanged("Key");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public object Value {
            get {
                return this.ValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ValueField, value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityReferenceOfEKeyVQpfUyxC", Namespace="http://schemas.datacontract.org/2004/07/System.Data.Objects.DataClasses")]
    [System.SerializableAttribute()]
    public partial class EntityReferenceOfEKeyVQpfUyxC : Sigeor.GestionAutenticacionServiceReference.EntityReference {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityReference", Namespace="http://schemas.datacontract.org/2004/07/System.Data.Objects.DataClasses")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Sigeor.GestionAutenticacionServiceReference.EntityReferenceOfEstructuraVQpfUyxC))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Sigeor.GestionAutenticacionServiceReference.EntityReferenceOfPerfilVQpfUyxC))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Sigeor.GestionAutenticacionServiceReference.EntityReferenceOfUsuarioVQpfUyxC))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Sigeor.GestionAutenticacionServiceReference.EntityReferenceOfEKeyVQpfUyxC))]
    public partial class EntityReference : Sigeor.GestionAutenticacionServiceReference.RelatedEnd {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Sigeor.GestionAutenticacionServiceReference.EntityKey EntityKeyField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Sigeor.GestionAutenticacionServiceReference.EntityKey EntityKey {
            get {
                return this.EntityKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.EntityKeyField, value) != true)) {
                    this.EntityKeyField = value;
                    this.RaisePropertyChanged("EntityKey");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RelatedEnd", Namespace="http://schemas.datacontract.org/2004/07/System.Data.Objects.DataClasses")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Sigeor.GestionAutenticacionServiceReference.EntityReference))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Sigeor.GestionAutenticacionServiceReference.EntityReferenceOfEstructuraVQpfUyxC))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Sigeor.GestionAutenticacionServiceReference.EntityReferenceOfPerfilVQpfUyxC))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Sigeor.GestionAutenticacionServiceReference.EntityReferenceOfUsuarioVQpfUyxC))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Sigeor.GestionAutenticacionServiceReference.EntityReferenceOfEKeyVQpfUyxC))]
    public partial class RelatedEnd : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityReferenceOfEstructuraVQpfUyxC", Namespace="http://schemas.datacontract.org/2004/07/System.Data.Objects.DataClasses")]
    [System.SerializableAttribute()]
    public partial class EntityReferenceOfEstructuraVQpfUyxC : Sigeor.GestionAutenticacionServiceReference.EntityReference {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityReferenceOfPerfilVQpfUyxC", Namespace="http://schemas.datacontract.org/2004/07/System.Data.Objects.DataClasses")]
    [System.SerializableAttribute()]
    public partial class EntityReferenceOfPerfilVQpfUyxC : Sigeor.GestionAutenticacionServiceReference.EntityReference {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityReferenceOfUsuarioVQpfUyxC", Namespace="http://schemas.datacontract.org/2004/07/System.Data.Objects.DataClasses")]
    [System.SerializableAttribute()]
    public partial class EntityReferenceOfUsuarioVQpfUyxC : Sigeor.GestionAutenticacionServiceReference.EntityReference {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="GestionAutenticacionServiceReference.IAutenticacionService")]
    public interface IAutenticacionService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAutenticacionService/ObtenerUsuarioPorCredenciales", ReplyAction="http://tempuri.org/IAutenticacionService/ObtenerUsuarioPorCredencialesResponse")]
        string ObtenerUsuarioPorCredenciales(string nombreUsuario, string contrasenia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAutenticacionService/CompararCoordenadaEkey", ReplyAction="http://tempuri.org/IAutenticacionService/CompararCoordenadaEkeyResponse")]
        bool CompararCoordenadaEkey(string coordenadaEKeyerializada);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAutenticacionService/ObtenerUsuarioPorEmail", ReplyAction="http://tempuri.org/IAutenticacionService/ObtenerUsuarioPorEmailResponse")]
        string ObtenerUsuarioPorEmail(string emailUsuario, string eKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAutenticacionService/InsertarEKey", ReplyAction="http://tempuri.org/IAutenticacionService/InsertarEKeyResponse")]
        void InsertarEKey(PersistenciaSigeor.EKey ekey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAutenticacionService/InsertarEKeyCoordenadasEkey", ReplyAction="http://tempuri.org/IAutenticacionService/InsertarEKeyCoordenadasEkeyResponse")]
        void InsertarEKeyCoordenadasEkey(PersistenciaSigeor.EKey ekey, System.Collections.Generic.List<PersistenciaSigeor.CoordenadasEkey> listaCoordenadasEkey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAutenticacionService/ModificarEKey", ReplyAction="http://tempuri.org/IAutenticacionService/ModificarEKeyResponse")]
        void ModificarEKey(PersistenciaSigeor.EKey ekey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAutenticacionService/EliminarEKey", ReplyAction="http://tempuri.org/IAutenticacionService/EliminarEKeyResponse")]
        void EliminarEKey(PersistenciaSigeor.EKey ekey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAutenticacionService/ObtenerEkeyPorCedulaUsuario", ReplyAction="http://tempuri.org/IAutenticacionService/ObtenerEkeyPorCedulaUsuarioResponse")]
        string ObtenerEkeyPorCedulaUsuario(string cedula);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAutenticacionService/ObtenerEkeyPorId", ReplyAction="http://tempuri.org/IAutenticacionService/ObtenerEkeyPorIdResponse")]
        string ObtenerEkeyPorId(System.Guid id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAutenticacionService/ObtenerEKey", ReplyAction="http://tempuri.org/IAutenticacionService/ObtenerEKeyResponse")]
        string ObtenerEKey();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAutenticacionService/ObtenerEKeyPorEstado", ReplyAction="http://tempuri.org/IAutenticacionService/ObtenerEKeyPorEstadoResponse")]
        string ObtenerEKeyPorEstado(bool estado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAutenticacionService/InsertarCoordenadasEkey", ReplyAction="http://tempuri.org/IAutenticacionService/InsertarCoordenadasEkeyResponse")]
        void InsertarCoordenadasEkey(PersistenciaSigeor.CoordenadasEkey coordenadasEkey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAutenticacionService/InsertarListaCoordenadasEkey", ReplyAction="http://tempuri.org/IAutenticacionService/InsertarListaCoordenadasEkeyResponse")]
        void InsertarListaCoordenadasEkey(System.Collections.Generic.List<PersistenciaSigeor.CoordenadasEkey> listaCoordenadasEkey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAutenticacionService/ModificarCoordenadasEkey", ReplyAction="http://tempuri.org/IAutenticacionService/ModificarCoordenadasEkeyResponse")]
        void ModificarCoordenadasEkey(PersistenciaSigeor.CoordenadasEkey coordenadasEkey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAutenticacionService/ModificarListaCoordenadasEkey", ReplyAction="http://tempuri.org/IAutenticacionService/ModificarListaCoordenadasEkeyResponse")]
        void ModificarListaCoordenadasEkey(System.Collections.Generic.List<PersistenciaSigeor.CoordenadasEkey> listaCoordenadasEkey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAutenticacionService/EliminarCoordenadasEkey", ReplyAction="http://tempuri.org/IAutenticacionService/EliminarCoordenadasEkeyResponse")]
        void EliminarCoordenadasEkey(PersistenciaSigeor.CoordenadasEkey coordenadasEkey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAutenticacionService/ObtenerCoordenadaEkeyPorId", ReplyAction="http://tempuri.org/IAutenticacionService/ObtenerCoordenadaEkeyPorIdResponse")]
        PersistenciaSigeor.CoordenadasEkey ObtenerCoordenadaEkeyPorId(System.Guid id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAutenticacionService/ObtenerCoordenadasEkeyPorIdEkey", ReplyAction="http://tempuri.org/IAutenticacionService/ObtenerCoordenadasEkeyPorIdEkeyResponse")]
        System.Collections.Generic.List<PersistenciaSigeor.CoordenadasEkey> ObtenerCoordenadasEkeyPorIdEkey(System.Guid idKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAutenticacionService/GenerarCoordenadasEkey", ReplyAction="http://tempuri.org/IAutenticacionService/GenerarCoordenadasEkeyResponse")]
        string GenerarCoordenadasEkey(string EKeyerializado);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAutenticacionServiceChannel : Sigeor.GestionAutenticacionServiceReference.IAutenticacionService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AutenticacionServiceClient : System.ServiceModel.ClientBase<Sigeor.GestionAutenticacionServiceReference.IAutenticacionService>, Sigeor.GestionAutenticacionServiceReference.IAutenticacionService {
        
        public AutenticacionServiceClient() {
        }
        
        public AutenticacionServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AutenticacionServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AutenticacionServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AutenticacionServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string ObtenerUsuarioPorCredenciales(string nombreUsuario, string contrasenia) {
            return base.Channel.ObtenerUsuarioPorCredenciales(nombreUsuario, contrasenia);
        }
        
        public bool CompararCoordenadaEkey(string coordenadaEKeyerializada) {
            return base.Channel.CompararCoordenadaEkey(coordenadaEKeyerializada);
        }
        
        public string ObtenerUsuarioPorEmail(string emailUsuario, string eKey) {
            return base.Channel.ObtenerUsuarioPorEmail(emailUsuario, eKey);
        }
        
        public void InsertarEKey(PersistenciaSigeor.EKey ekey) {
            base.Channel.InsertarEKey(ekey);
        }
        
        public void InsertarEKeyCoordenadasEkey(PersistenciaSigeor.EKey ekey, System.Collections.Generic.List<PersistenciaSigeor.CoordenadasEkey> listaCoordenadasEkey) {
            base.Channel.InsertarEKeyCoordenadasEkey(ekey, listaCoordenadasEkey);
        }
        
        public void ModificarEKey(PersistenciaSigeor.EKey ekey) {
            base.Channel.ModificarEKey(ekey);
        }
        
        public void EliminarEKey(PersistenciaSigeor.EKey ekey) {
            base.Channel.EliminarEKey(ekey);
        }
        
        public string ObtenerEkeyPorCedulaUsuario(string cedula) {
            return base.Channel.ObtenerEkeyPorCedulaUsuario(cedula);
        }
        
        public string ObtenerEkeyPorId(System.Guid id) {
            return base.Channel.ObtenerEkeyPorId(id);
        }
        
        public string ObtenerEKey() {
            return base.Channel.ObtenerEKey();
        }
        
        public string ObtenerEKeyPorEstado(bool estado) {
            return base.Channel.ObtenerEKeyPorEstado(estado);
        }
        
        public void InsertarCoordenadasEkey(PersistenciaSigeor.CoordenadasEkey coordenadasEkey) {
            base.Channel.InsertarCoordenadasEkey(coordenadasEkey);
        }
        
        public void InsertarListaCoordenadasEkey(System.Collections.Generic.List<PersistenciaSigeor.CoordenadasEkey> listaCoordenadasEkey) {
            base.Channel.InsertarListaCoordenadasEkey(listaCoordenadasEkey);
        }
        
        public void ModificarCoordenadasEkey(PersistenciaSigeor.CoordenadasEkey coordenadasEkey) {
            base.Channel.ModificarCoordenadasEkey(coordenadasEkey);
        }
        
        public void ModificarListaCoordenadasEkey(System.Collections.Generic.List<PersistenciaSigeor.CoordenadasEkey> listaCoordenadasEkey) {
            base.Channel.ModificarListaCoordenadasEkey(listaCoordenadasEkey);
        }
        
        public void EliminarCoordenadasEkey(PersistenciaSigeor.CoordenadasEkey coordenadasEkey) {
            base.Channel.EliminarCoordenadasEkey(coordenadasEkey);
        }
        
        public PersistenciaSigeor.CoordenadasEkey ObtenerCoordenadaEkeyPorId(System.Guid id) {
            return base.Channel.ObtenerCoordenadaEkeyPorId(id);
        }
        
        public System.Collections.Generic.List<PersistenciaSigeor.CoordenadasEkey> ObtenerCoordenadasEkeyPorIdEkey(System.Guid idKey) {
            return base.Channel.ObtenerCoordenadasEkeyPorIdEkey(idKey);
        }
        
        public string GenerarCoordenadasEkey(string EKeyerializado) {
            return base.Channel.GenerarCoordenadasEkey(EKeyerializado);
        }
    }
}
